### PR TITLE
Support MTU size setting for nodes other than admin and storage.

### PR DESCRIPTION
**Pull request by mmnelemane**
Alllows setting mtu size for nodes using "want_mtu_size" variable. Set want_mtu_size="jumbo" to enable jumbo frame testing.

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
schema update, revision bump and migrations are missing...
have a look here how it needs to be done https://github.com/crowbar/barclamp-nova/pull/476

**Comment by rsalevsky** [comment]
@MaximilianMeister It's not needed here, was already done in a previous PR.

**Comment by MaximilianMeister** [comment]
@rsalevsky @mmnelemane which one? that should be mentioned at least in the commit message. so this is only a fixup for an old PR?

**Comment by tboerger** [comment]
LGTM

**Comment by rsalevsky** [comment]
+1 but let's wait for the gating test

**Comment by aspiers** [comment]
Agree with @MaximilianMeister - please can you mention the previous PR URL in the commit message? Thanks!

**Pull request closed without merging**
