### PR TITLE
add some API documentation

### PR DESCRIPTION
**Pull request by MaximilianMeister**
this renders a static site which is currently at `/apidoc` (in this configuration)

https://github.com/Apipie/apipie-rails

screenshot from 2016-06-30 13-45-00

### CODE REVIEW

**Comment by toabctl** [comment]
I think you need to add ```apipie``` to the media to get gating green, right? Failure is ```Could not find gem 'apipie-rails (~> 0.3.6) ruby```.
And is it possible to add a spec test?

**Comment by MaximilianMeister** [comment]
> I think you need to add apipie to the media to get gating green, right? Failure is Could not find gem 'apipie-rails (~> 0.3.6) ruby.

yes, thanks for the reminder. I had to do other work and this got a bit forgotten...

> And is it possible to add a spec test?

not sure what to test here... any idea?

**Comment by rsalevsky** [comment]
+1

**Comment by nicolasbock** [comment]
+1

**Pull request merged**
