### PR TITLE
network: restore default route after 'wicked ifup all' (bsc#1075368)

### PR DESCRIPTION
**Pull request by stefannica**
https://bugzilla.suse.com/show_bug.cgi?id=1075368

In some cases, the 'wicked ifup all' call executed after the
network barclamp updates all wicked and sysconfig configuration files
has the unwanted effect that it removes the default route.

This PR adds a step that restores the default route when missing.

Several other solutions have been attempted, without success (see 
bsc#1075368).

### CODE REVIEW

**Comment by susecloudcommitpolice** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please limit commit subject line to 50 characters.<br />
cf0150687dfb1d9fe9a3c95ddaecd605535b46d2</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="http://danger.systems/">Danger</a>
</p>

**Comment by s-t-e-v-e-n-k** [comment]
I think it was first introduced in https://github.com/crowbar/crowbar-core/pull/821, reworked in https://github.com/crowbar/crowbar-core/pull/868, corrected in https://github.com/crowbar/crowbar-core/pull/1150 and reverted in https://github.com/crowbar/crowbar-core/pull/1207.

**Comment by nicolasbock** [comment]
Thanks for doing some forensics on this @s-t-e-v-e-n-k ! I think it would be great to add these findings to the commit message @stefannica .

**Comment by stefannica** [comment]
Thanks @s-t-e-v-e-n-k , that was very useful. Unfortunately, that also leaves me without a cheap solution for this bug, hence marking this as WIP for the time being.

**Comment by stefannica** [comment]
> I think it was first introduced in #821, reworked in #868, corrected in #1150 and reverted in #1207.

Then, it was later partially re-introduced in #1239, only `ifreload` was replaced with `ifup`.

**Comment by rhafer** [comment]
> Then, it was later partially re-introduced in #1239, only ifreload was replaced with ifup.

Right, this was done after consulting once more with the wicked developers. ifup (in contrast to ifreload) does not remove any pacemaker managed VIPs from the interfaces (https://bugzilla.suse.com/show_bug.cgi?id=1032751).

**Pull request merged**
