### PR TITLE
fix broken link to documentation resources

### PR DESCRIPTION
**Pull request by MaximilianMeister**
since the docs_controller is now activated we can link to the view

### CODE REVIEW

**Comment by vuntz** [comment]
Hrm, but the docs view has a navigation bar, doesn't it?

**Comment by MaximilianMeister** [comment]
closing for now in favor patching the branding in https://github.com/SUSE-Cloud/crowbar-core/commit/9acea36234807af4ee3cba00897706366ea37a7e

**Comment by vuntz** [comment]
For the record, another issue is that the page redirects to the installer in install mode ;-)

**Comment by MaximilianMeister** [comment]
@vuntz ouh... then we need to skip the filter for the docs controller, i think we already had that once and took it out again... another issue is do you think it makes sense to add a link to the release notes as well in the branding?

**Comment by tboerger** [comment]
Why have this been closed?

**Pull request closed without merging**
