### PR TITLE
provisioner: cleanup hyperv files

### PR DESCRIPTION
**Pull request by bmwiedemann**
saving ~63MB disk space and bandwidth

The total crowbar-core is 65MB atm, and it turned out, most of that
is not needed anymore.

### CODE REVIEW

**Comment by bmwiedemann** [comment]
The master version introduced some regression https://ci.suse.de/job/openstack-mkcloud/100076/parsed_console/ so we need to get that fixed first and then add the fix to this backport.

**Comment by bmwiedemann** [comment]
I squashed the fixups from #1467 into this, but I could add the commit IDs to this commit message once the 1467 is good and merged.

**Comment by nicolasbock** [comment]
Yes, I think that would be a good idea, if purely from a forensics point of view :)

**Comment by bmwiedemann** [comment]
should be good to merge now.

**Comment by dirkmueller** [comment]
does this work for the maintenance update case? I don't see a migration added and we are editing a proposal template..

**Comment by dirkmueller** [comment]
not relevant for SOC7 anymore.

**Pull request closed without merging**
