### PR TITLE
[4.0] Allow pacemaker remotes for upgrade (SOC-10133)

### PR DESCRIPTION
**Pull request by jgrassler**
This commit allows clouds with Pacemaker remote nodes to be
upgraded. To this end it changes the upgrade precheck to
include remote nodes in the list of valid elements.

Please do not merge this, yet. We can only merge it once all other changes required for SOC-10133 have landed and we have verified the upgrade works.

### CODE REVIEW

**Comment by jsuchome** [comment]
Actually, this does not need a forward port exactly, as we forgot to port https://github.com/crowbar/crowbar-core/pull/1684 into 5.0.
But I think we should port the old PR together with the fix that is present here.

**Comment by jsuchome** [comment]
Needs rebase after merging https://github.com/crowbar/crowbar-core/pull/1953

**Comment by jsuchome** [comment]
... and another rebase after https://github.com/crowbar/crowbar-core/pull/1972

**Comment by jgrassler** [comment]
Needs https://github.com/crowbar/crowbar-core/pull/1972 for travis to pass.

**Comment by jgrassler** [comment]
Rebase done. I removed the needs-forward-port label as well since we've got no equivalent of this precheck in Cloud 8 anyway.

**Pull request merged**
