### PR TITLE
bsc#966356 selectors were OR chained, not AND

### PR DESCRIPTION
**Pull request by MaximilianMeister**
https://bugzilla.suse.com/show_bug.cgi?id=966356

### CODE REVIEW

**Comment by jsuchome** [comment]
Seems to help. +1

**Comment by vuntz** [comment]
Would you mind updating the commit message. It feels like it should be something like:

```
crowbar: Fix blockui appearing nearly all the time (bsc#966356)

selectors were OR chained, not AND

https://bugzilla.suse.com/show_bug.cgi?id=966356
```

**Comment by vuntz** [comment]
So this more or less reverts https://github.com/crowbar/crowbar-core/commit/2bd6bf0dd73d14bcb93069eb4bbe7fbf0cf964fb

@rsalevsky what was the reason behind that change?

**Comment by vuntz** [comment]
+1

**Comment by MaximilianMeister** [comment]
https://github.com/crowbar/crowbar-core/commit/2bd6bf0dd73d14bcb93069eb4bbe7fbf0cf964fb has worked on the pages where we wanted it to work (before with the descendant selector it somehow didn't)

but it has not been noticed that it also works on the barclamp pages, where we have $([data-blockui]) as well, but we didn't want it there...

**Comment by rsalevsky** [comment]
+1 tested in the wizard

**Pull request merged**
