### PR TITLE
upgrade: Allow manila-share role on compute nodes.

### PR DESCRIPTION
**Pull request by jsuchome**
Nodes with manila-share node do not need to be treated as non-compute nodes.

### CODE REVIEW

**Comment by jsuchome** [comment]
There might be more required...

**Comment by susecloudcommitpolice** [comment]
<table>
  <thead>
    <tr>
      <th width="50"></th>
      <th width="100%" data-danger-table="true" data-kind="Warning">
          1 Warning
      </th>
     </tr>
  </thead>
  <tbody>
    <tr>
      <td>:warning:</td>
      <td data-sticky="false">Please remove period from end of commit subject line.<br />
455fc3f8d7c6b1a47c9648a262968130ac1ff232</td>
    </tr>
  </tbody>
</table>

<p align="right" data-meta="generated_by_danger">
  Generated by :no_entry_sign: <a href="https://danger.systems/">Danger</a>
</p>

**Comment by s-t-e-v-e-n-k** [comment]
I am fine with this change, but running crowbarctl upgrade node controllers still resulted in the compute node being upgraded with it applied.

**Comment by jsuchome** [comment]
This PR is correct if we want to allow manila share on compute nodes, but do we? 
Please check SCRD-3571

**Pull request closed without merging**
