### PR TITLE
Revert "Revert "Stop writing dev file for rainbows, bin/rails server …

### PR DESCRIPTION
**Pull request by MaximilianMeister**
…is the thruth""

This reverts commit c2112fe9a24a2c914f78a95e6d6031bff8fe5ec5.

This revert in c2112fe9a24a2c914f78a95e6d6031bff8fe5ec5 wouldn't have been necessary in the first revert, that's why we revert the revert here.

### CODE REVIEW

**Comment by rsalevsky** [comment]
+1

**Comment by tboerger** [comment]
:+1:

**Comment by aspiers** [comment]
It seems this is reverting part of https://github.com/crowbar/barclamp-crowbar/pull/1338

**Comment by tboerger** [comment]
> It seems this is reverting part of crowbar/barclamp-crowbar#1338

Really? And as @MaximilianMeister said, this was a useless revert.

**Comment by aspiers** [comment]
@tboerger Really what?  I'm not disputing the change, merely adding a link for future reference.  This PR only referenced the individual commit being reverted (https://github.com/crowbar/crowbar-core/commit/c2112fe9a24a2c914f78a95e6d6031bff8fe5ec5), but https://github.com/crowbar/barclamp-crowbar/pull/1338 contains more useful context.

**Comment by dirkmueller** [comment]
LGTM

**Comment by tboerger** [comment]
> @tboerger Really what? I'm not disputing the change, merely adding a link for future reference. This PR only referenced the individual commit being reverted (c2112fe), but crowbar/barclamp-crowbar#1338 contains more useful context.

Because the revert pull request doesn't really matter as this was simply a wrong revert. This commit has nothing to do with breaking anything as it just drops the creation of the rainbows-dev config which is anyway not used by somebody these days.

**Comment by aspiers** [comment]
@tboerger Sounds like you still think I was questioning the change.  I am not!  I just found the context hard to understand without a link to https://github.com/crowbar/barclamp-crowbar/pull/1338, so I added it in case anyone else had the same problem.

**Pull request merged**
