### PR TITLE
Remove unused cookbooks

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by rsalevsky** [comment]
Travis fails...

**Comment by tboerger** [comment]
@vuntz you need to remove the rails part from the rspec fixtures.

**Comment by vuntz** [comment]
Just to make it clear: gating can't be green because the patch fails when building the package (due to the removal of binary files).

**Comment by rsalevsky** [comment]
+1

**Comment by tboerger** [comment]
:+1:

**Pull request merged**
