### PR TITLE
network: check for duplicate ip addr (SOC-11102)

### PR DESCRIPTION
**Pull request by sandonovsuse**
Crowbar doesn't check for duplicate IP addresses in the network prior to
adding the address to the interface. This patch adds this functionality,
with chef run failing if duplicate IP address detected.

### CODE REVIEW

**Comment by jsuchome** [comment]
Why is it a problem?

**Comment by sandonovsuse** [comment]
> Why is it a problem?

A use  case where IP addresses allocated in crowbar during deployment for any of the network ranges are taken at some later point in time by some other devices external to cloud, i.e. external ceph deployment residing in network range allocated to crowbar storage network. Now deploying a new node might end up in setting a duplicate IP address in storage subnet due to chef not checking for duplicate address prior to setting it. This commit only checks for duplicate and if one is detected it fails the chef run until the conflict is resolved by admin.

**Comment by skazi0** [comment]
Is this even a supported scenario? Shouldn't external nodes use range which doesn't overlap the one in Crowbar?

**Comment by sandonovsuse** [comment]
Yes, I don't think it is a supported scenario, although it may happen years after deployment when it's too late to change crowbar ranges (bsc#1163563). This patch would fail the chef-run only if such a scenario took place (even though it is unsupported), otherwise it should act the same way on a supported deployment scenario

**Comment by sandonovsuse** [comment]
Rebased

**Comment by JanZerebecki** [comment]
The ticket was closed as "Won't do". Please reopen if you think this is useful.

**Pull request closed without merging**
