### PR TITLE
api cleanup: move business logic into the model

### PR DESCRIPTION
**Pull request by MaximilianMeister**

### CODE REVIEW

**Comment by jsuchome** [comment]
@MaximilianMeister Do you want me to adapt https://github.com/crowbar/crowbar-core/pull/661 this way, or should we rather merge that one and do the cleanup as part of your PR?

Some other calls should be adapted as well (`prepare`), and for some model methods we'll change the return values, I think (`prechecks`)

**Comment by MaximilianMeister** [comment]
> Do you want me to adapt #661 this way, or should we rather merge that one and do the cleanup as part of your PR?

I can add it here after the merge, no problem

**Comment by jsuchome** [comment]
What about `prepare` ?

**Comment by MaximilianMeister** [comment]
> What about prepare ?

lets wait for the outcome of https://github.com/crowbar/crowbar-core/pull/660

**Comment by abel-navarro** [comment]
+1

**Comment by jsuchome** [comment]
+1

**Pull request merged**
