### PR TITLE
provisioner: Use tftp.service on SLE12 instead of xinetd

### PR DESCRIPTION
**Pull request by vuntz**
systemd can do the work for us.

WIP because the tftp service is missing a way to specify the mapping file that we use.

### CODE REVIEW

**Comment by tboerger** [comment]
LGTM

**Comment by rsalevsky** [comment]
+1 but please fix the hound issue

**Comment by vuntz** [comment]
https://ci.suse.de/job/openstack-mkcloud/10560 is a gating build with all the patches required.

**Comment by vuntz** [comment]
Nodes were allocated in the job, so it seems tftp is working.

**Comment by MaximilianMeister** [comment]
:+1: ( shall we wait for gating to finish? )

**Comment by vuntz** [comment]
@MaximilianMeister I'm fine waiting, but we can't merge right now anyway since we're missing a +1 on https://github.com/crowbar/crowbar/pull/2175

**Comment by rsalevsky** [comment]
Still +1

**Pull request merged**
