### PR TITLE
increase crowbar version for API enpoint /crowbar/:barclamp

### PR DESCRIPTION
**Pull request by MaximilianMeister**

### CODE REVIEW

**Comment by vuntz** [comment]
Can you explain why in the commit message?

**Comment by MaximilianMeister** [comment]
not sure now, maybe this stands for the API version? then the would be wrong. I thought this refers to the crowbar version. do you have an idea @vuntz ?

**Comment by vuntz** [comment]
I think it's the API version.

**Comment by MaximilianMeister** [comment]
closing, as this doesn't refer to the crowbar version

**Pull request closed without merging**
