### PR TITLE
ip_local_port_range needs to have different parity for start/end values

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by toabctl** [comment]
@dirkmueller I have no idea why that is needed. Can you exlain that a bit?

**Comment by rhafer** [comment]
> I have no idea why that is needed. Can you exlain that a bit?

@toabctl I guess the answer to that is related to this kernel commit: http://kernel.suse.com/cgit/kernel/commit/?id=07f4c90062f8f and this which added a warning: http://www.spinics.net/lists/netdev/msg330895.html

I just stumbled of that while looking for something completely different.

**Comment by dirkmueller** [comment]
@rhafer updated documentation

**Comment by rhafer** [comment]
+1

**Comment by nicolasbock** [comment]
+1

**Pull request merged**
