### PR TITLE
Add more NIC speeds to crowbar ohai plugin

### PR DESCRIPTION
**Pull request by rhafer**

### CODE REVIEW

**Comment by vuntz** [comment]
s/All/Allow/ in the second commit message

**Comment by vuntz** [comment]
+1 after the commit message fix

**Comment by aplanas** [comment]
+1

**Comment by nicolasbock** [comment]
+1

**Comment by vuntz** [comment]
Will you backport to stable/3.0?

**Comment by rhafer** [comment]
@vuntz Yeah, it's here: https://github.com/crowbar/crowbar-core/pull/626

**Pull request merged**
