### PR TITLE
crowbar: Fix upgrade from 3.0

### PR DESCRIPTION
**Pull request by vuntz**
The proposals in 3.0 were already in the database (and not chef
anymore), but still need to be migrated with the scema migrations.

### CODE REVIEW

**Comment by aplanas** [comment]
+1

cc @nicolasbock r?

**Comment by nicolasbock** [comment]
I can't test this right now, but assuming it passes it looked great!

:+1:

**Comment by vuntz** [comment]
Note that I haven't tested, this was just the quick patch @nicolasbock and I wrote, but I didn't have time to go further :/

**Comment by nicolasbock** [comment]
@vuntz I have already prepared a test setup. This week I am out on vacation, but will have time to test this patch during a cloud upgrade in a few days.

**Comment by nicolasbock** [comment]
+1/2

I verified that this PR works when I run
~~~
cd /opt/dell/crowbar_framework
RAILS_ENV=production rake crowbar:schema_migrate[heat]
~~~
This does not cover the whole patch though. I am currently trying to inject this patch into the upgrade process to test it completely.

**Comment by nicolasbock** [comment]
Closing as this PR is superseded by https://github.com/crowbar/crowbar-core/issues/491

**Pull request closed without merging**
