### PR TITLE
crowbar: Fix system() call when creating backup

### PR DESCRIPTION
**Pull request by vuntz**
It was failing when the name of the archive had a space, and... it was
allowing command injection.

### CODE REVIEW

**Comment by aplanas** [comment]
+1

**Comment by bmwiedemann** [comment]
+1

**Comment by MaximilianMeister** [comment]
as I see now the structure of the tarball has changed (I am just guessing that it is due to this PR due to the timestamp)

```
drwxr-xr-x crowbar/crowbar   0 2016-02-12 13:51 crowbar/
drwxr-xr-x crowbar/crowbar   0 2016-02-12 13:51 crowbar/root/
...
...
```

and now it has a different structure, was that wanted?

```
drwx------ crowbar/crowbar   0 2016-02-15 09:06 ./
drwxr-xr-x crowbar/crowbar   0 2016-02-15 09:06 ./crowbar/
...
...
```

**Comment by vuntz** [comment]
It's a side-effect of moving from "tar czf foo.tar *" to "tar czf foo.tar ." -- but it doesn't harm.

**Pull request merged**
