### PR TITLE
webui: Rewrite help page to be more friendly for downstreams

### PR DESCRIPTION
**Pull request by vuntz**
We now parse a yaml file that describes the various guides that should
be displayed on the help page.

### CODE REVIEW

**Comment by tboerger** [comment]
Than you should remove or integrate all the other markdown files within the doc folder as well :)

**Comment by vuntz** [comment]
> Than you should remove or integrate all the other markdown files within the doc folder as well :)

done

**Comment by tboerger** [comment]
:+1:

Do you create a PR for openstack as well? Maybe we need a doc.yml folder to integrate the docs from other barclamps as well like openstack, e.g. `config/doc/crowbar.yml`, `config/doc/openstack.yml`, `config/doc/hadoop.yml`?

**Comment by vuntz** [comment]
Not sure why hound is red, but gating can't be green as this PR conflicts with the packaging.

**Comment by tboerger** [comment]
Hound just failed to clone the repo on their side. I think you have to update the code to accept a directory of yml files to be able to generate the documentation links for multiple sources. I would suggest `crowbar_framework/config/docs/**/*` as a globbing rule.

**Comment by vuntz** [comment]
Thaks @tboerger for the fixes! For reference, this looks like:
screenshot

**Comment by vuntz** [comment]
Not sure if it counts, but +1 for changes done by @tboerger.

**Comment by tboerger** [comment]
:+1: for the current state. In the future it can be interesting to render HTML out of the `.md` files.

**Comment by aplanas** [comment]
+1

**Comment by vuntz** [comment]
For the record: gating can't pass because this conflicts with the branding.

**Comment by tboerger** [comment]
So lets merge this and the openstack pull request.

**Pull request merged**
