### PR TITLE
[stable/3.0] upgrade: Check if there are any failed proposals before starting the upgrade

### PR DESCRIPTION
**Pull request by jsuchome**
```
# crowbarctl upgrade prechecks
+-------------------------------+--------+----------+-----------------------------------------------------+-------------------------------------------------------------------------------------------------------+
| Check ID                      | Passed | Required | Errors                                              | Help                                                                                                  |
+-------------------------------+--------+----------+-----------------------------------------------------+-------------------------------------------------------------------------------------------------------+
| network_checks                | true   | true     |                                                     |                                                                                                       |
| failed_proposals              | false  | true     | "These proposals report deployment failures: Nova." | "Check the state of the specific barclamps and redeploy them correctly or disable failing proposals." |
| maintenance_updates_installed | true   | true     |                                                     |                                                                                                       |
| ha_configured                 | true   | false    |                                                     |                                                                                                       |
| clusters_healthy              | true   | true     |                                                     |                                                                                                       |
+-------------------------------+--------+----------+-----------------------------------------------------+-------------------------------------------------------------------------------------------------------+
Make sure that there are no errors for the required checks before executing the next step.
Next step: 'crowbarctl upgrade prepare'
```

### CODE REVIEW

**Comment by jsuchome** [comment]
[(3) S53P5 (S41P12): Validate that there are no unapplied changes before upgrade or proposals in error state (#demo) #UX](https://trello.com/c/4U3OriFU/253-3-s53p5-s41p12-validate-that-there-are-no-unapplied-changes-before-upgrade-or-proposals-in-error-state-demo-ux)

**Comment by jsuchome** [comment]
@skazi0 this implies another key to be checked in the UI...

**Comment by MaximilianMeister** [comment]
@jsuchome no unit test?

**Comment by jsuchome** [comment]
Hm, good point, some test should be here...

**Comment by jsuchome** [comment]
@MaximilianMeister unit tests added

**Comment by skazi0** [comment]
@jsuchome as far as I can see there's no new check here, just a new possible error code. The only thing needed for these in the UI is translations.

**Comment by jsuchome** [comment]
@skazi0 yes, I mean error code

**Comment by skazi0** [comment]
tested and working

**Pull request merged**
