### PR TITLE
Don't create ovs-system related pieces anymore

### PR DESCRIPTION
**Pull request by rhafer**
They are no longer needed with the latest wicked (>= 0.6.28)

### CODE REVIEW

**Comment by toabctl** [comment]
+1

**Comment by vuntz** [comment]
+1 if gating is green :-)

**Comment by rhafer** [comment]
@vuntz it's not exactly green :), but survived tempest and AFAICS cct failed just because the chef-client run was so slow that crowbar considered the node state "unknown".

**Comment by vuntz** [comment]
@rhafer does this survive a reboot?

**Comment by rhafer** [comment]
> does this survive a reboot?

@vuntz yes. At least on my manual deployment. Hm, probably I'll just retrigger the CI  with reboot enabled.

**Comment by rhafer** [comment]
@vuntz that last ci run was with reboot enable. YAY!

**Pull request merged**
