### PR TITLE
[3.0] delete backup tmpdir

### PR DESCRIPTION
**Pull request by rsalevsky**

### CODE REVIEW

**Comment by vuntz** [comment]
Backport of https://github.com/crowbar/crowbar-core/pull/339

(I'm assuming the change in the specs is not needed due to another change not being backported yet)

+1

**Comment by MaximilianMeister** [comment]
> I'm assuming the change in the specs is not needed due to another change not being backported yet

why not backport https://github.com/crowbar/crowbar-core/pull/348 before this and add the change with the specs here?

**Comment by vuntz** [comment]
> why not backport #348 before this and add the change with the specs here?

#348 got backported now, so I guess the change is needed now?

**Comment by MaximilianMeister** [comment]
I see you added back the spec change, thanks

+1

**Comment by vuntz** [comment]
Thanks, +1.

**Comment by rsalevsky** [comment]
Travis failed due to CVE tests.

**Pull request merged**
