### PR TITLE
add specs for the Crowbar::Backup::Export library

### PR DESCRIPTION
**Pull request by MaximilianMeister**

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
really no idea why travis fails... locally it is all green. @tboerger @rsalevsky any idea?

**Comment by vuntz** [comment]
LGTM

**Comment by rsalevsky** [comment]
+1

**Comment by MaximilianMeister** [comment]
@tboerger can you please have a look here?

**Comment by tboerger** [comment]
Cool
:+1:

**Comment by tboerger** [comment]
> This branch is out-of-date with the base branch

**Comment by MaximilianMeister** [comment]
all green, merging

**Pull request merged**
