### PR TITLE
delayed_job: require delayed_job when starting crowbar service

### PR DESCRIPTION
**Pull request by MaximilianMeister**

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
gating will fail until https://build.suse.de/request/show/125531 is closed

**Comment by MaximilianMeister** [comment]
[(5) perform more upgrade actions in the background](https://trello.com/c/qjZy2nuP/202-5-perform-more-upgrade-actions-in-the-background)

**Comment by MaximilianMeister** [comment]
I've changed the pid directory to `/run/tmpfiles.d` thanks to @dirkmueller suggestion.
https://github.com/SUSE-Cloud/automation/pull/1537 is also merged, lets see what the next gating says...

**Comment by MaximilianMeister** [comment]
`/run/tmpfiles.d` is only writable by root, so I have now placed the pid files to `crowbar_framework/tmp/pids` which is also used by puma to store the pid files

**Comment by rsalevsky** [comment]
Would be good to have gating here.

**Pull request merged**
