### PR TITLE
[3.0] Avoid exporting backups in the backup

### PR DESCRIPTION
**Pull request by MaximilianMeister**
Backport of https://github.com/crowbar/crowbar-core/pull/326

### CODE REVIEW

**Comment by aspiers** [comment]
@MaximilianMeister Please read line 80 of https://etherpad.nue.suse.com/p/cloud-PR-porting :-)

**Comment by aspiers** [comment]
At a guess this needs rebasing to fix Travis.

**Comment by MaximilianMeister** [comment]
> @MaximilianMeister Please read line 80 of https://etherpad.nue.suse.com/p/cloud-PR-porting :-)

Ok I have read it, what's the violation?

**Comment by aspiers** [comment]
@MaximilianMeister I changed the PR title to fix the violation.

**Comment by MaximilianMeister** [comment]
> I changed the PR title and description to (partially) fix the violation.

@aspiers ok. i missed that bit. now i see

**Pull request merged**
