### PR TITLE
Fix deactivation of proposals to really remove roles from nodes

### PR DESCRIPTION
**Pull request by vuntz**
This is a recent regression from https://github.com/crowbar/crowbar-core/pull/515

### CODE REVIEW

**Comment by toabctl** [comment]
@vuntz travis failed.

**Comment by vuntz** [comment]
> @vuntz travis failed.

Was already fixing it :-) And that's done.

**Comment by toabctl** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Pull request merged**
