### PR TITLE
Update in_process led animation (SCRD-8786)

### PR DESCRIPTION
**Pull request by eapodaca**
* Updates led animations to be more apparent and easy to see.
* Updates all led animations to use css animations so they blink at the same rate.

### CODE REVIEW

**Comment by eapodaca** [comment]
I don't understand why hound is complaining.

**Comment by skazi0** [comment]
> I don't understand why hound is complaining.

Because it's a dog :o)

**Comment by eapodaca** [comment]
The thing is... all that worked before for one of my other PRs ¯\\\_(ツ)_/¯

**Comment by skazi0** [comment]
@eapodaca I merged the hound fix. Please (force)push something here to retrigger hound.

**Comment by jeremy-moffitt** [comment]
the error in the ha test does not look related to this change
```
sshrun TIMEFORMAT="timing for mkcloud call 'onadmin_testsetup' real=%R user=%U system=%S" ; time onadmin_testsetup failed! (safelyret=102) Aborting.
```

**Comment by dirkmueller** [comment]
Would it not make sense to have the 'inprogress' blink differently? Not that I care much though, but how do we indicate that the visible state is not final?

**Pull request merged**
