### PR TITLE
Revert "Old cli tools wrapper rewrite"

### PR DESCRIPTION
**Pull request by toabctl**
Reverts crowbar/crowbar-core#129

### CODE REVIEW

**Comment by aplanas** [comment]
Reasons: https://github.com/crowbar/crowbar-core/pull/129#issuecomment-165244279 and https://github.com/crowbar/crowbar-core/pull/129#issuecomment-165302524

**Comment by MaximilianMeister** [comment]
:+1: for now unless there is a quicker fix (but maybe we have to adapt the gating to use `crowbar_batch` and deploy `pacemaker` as well ?)

**Comment by tboerger** [comment]
So somebody else can take this pr. How should I work if even the test environment doesn't work like expected? Core components like pacemaker are not tested at all? Awesome...

**Comment by toabctl** [comment]
> So somebody else can take this pr. How should I work if even the test environment doesn't work like expected? Core components like pacemaker are not tested at all? Awesome...

We have only basic testing due to limited hardware resources. But you can run the tests multiple times with different parameters...

**Pull request merged**
