### PR TITLE
ignore .bundle/config and vendor/

### PR DESCRIPTION
**Pull request by aspiers**

### CODE REVIEW

**Comment by tboerger** [comment]
Why?

**Comment by aspiers** [comment]
Because at one point I did `bundle config path vendor/bundle` to [stop `bundle` installing gems system-wide via `sudo` without my permission](https://github.com/bundler/bundler/issues/3006).

**Comment by vuntz** [comment]
No strong opinion, so +1 if that helps you.

**Comment by tboerger** [comment]
A better description within the commit, afterwards :+1:

**Comment by aspiers** [comment]
@tboerger Thanks - commit adjusted.

**Pull request merged**
