### PR TITLE
webui: Add favicon option in branding to help downstreams

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by tboerger** [comment]
:+1: for now until we rebuild the branding with the possibility to build subpackages.

**Comment by vuntz** [comment]
@tboerger that's actually to enable this that this change is done ;-)

**Comment by tboerger** [comment]
> @tboerger that's actually to enable this that this change is done ;-)

Because of that I gave my :+1: :)

**Comment by rsalevsky** [comment]
:+1:

**Comment by vuntz** [comment]
Gating is red because it conflicts with the branding patch...

**Pull request merged**
