### PR TITLE
crowbar: Add missing files to backup

### PR DESCRIPTION
**Pull request by vuntz**
At least on tex, we backup these files...

### CODE REVIEW

**Comment by rhafer** [comment]
I think this is not the right fix.  The needed files are listed in ```restore_files_after_install``` you just have to fix creating the list in ```export_files``` https://github.com/vuntz/crowbar-core/blob/fix-backup/crowbar_framework/lib/crowbar/backup/base.rb#L114

I seem that just takes first item of ```restore_files_after_install```

**Comment by vuntz** [comment]
Ah, yes, thanks.

**Comment by vuntz** [comment]
A quick test with no node and no proposal shows that it seems to work.

**Comment by rhafer** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Comment by MaximilianMeister** [comment]
does the 2nd commit help after all?

**Comment by vuntz** [comment]
> does the 2nd commit help after all?

I've removed it.

**Comment by aplanas** [comment]
+1

**Comment by MaximilianMeister** [comment]
+1

**Pull request merged**
