### PR TITLE
Check if repository is physically available.

### PR DESCRIPTION
**Pull request by jsuchome**
I'm not sure why this check was missing, possibly there was a reason for that? @MaximilianMeister

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
can't say without investigating. better ask @vuntz who wrote it. maybe he knows a quick answer

**Comment by rhafer** [comment]
Makes sense to me. +1

**Comment by jsuchome** [comment]
@vuntz do you know this code?

**Comment by vuntz** [comment]
+1; the code change is really just a fix from the previous PR (https://github.com/crowbar/crowbar-core/pull/188/files)

**Comment by rhafer** [comment]
+1

**Comment by jsuchome** [comment]
@vuntz I'm not against your +1, but it is not a fix of previous PR, the check for availability of repo was never really there.

**Comment by vuntz** [comment]
Well, it was kind of implicit wit the `active?` check :-)

**Comment by jsuchome** [comment]
Hm, to me `active?` seems to only look at yml file value, but maybe I'm missing something

**Pull request merged**
