### PR TITLE
crowbar: Add rake task and cron job to sweep sessions from database

### PR DESCRIPTION
**Pull request by vuntz**
This is not done automatically by rails, and is important to do. See
http://guides.rubyonrails.org/security.html#session-expiry

### CODE REVIEW

**Comment by aplanas** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Comment by vuntz** [comment]
Hrm, should we change the crowbar cookbook to also install such a cron job?

**Comment by tboerger** [comment]
https://github.com/rails/activerecord-session_store/pull/37/files :)

**Comment by dirkmueller** [comment]
+1

**Pull request merged**
