### PR TITLE
[stable/3.0] backport #343

### PR DESCRIPTION
**Pull request by MaximilianMeister**
#343

### CODE REVIEW

**Comment by vuntz** [comment]
+1

**Comment by vuntz** [comment]
@MaximilianMeister travis is failing with a real error here.

**Comment by MaximilianMeister** [comment]
> travis is failing with a real error here.

@vuntz yeah a rebase was necessary. should be good now.

**Comment by vuntz** [comment]
Thanks, still +1

**Comment by rsalevsky** [comment]
+1

**Pull request merged**
