### PR TITLE
Add utils_systemd_service_restart LWRP

### PR DESCRIPTION
**Pull request by vuntz**
This resource adds (or removes) a systemd config snippet for a service,
to change the behavior to Restart=on-failure for that service. This
means systemd will automatically restart the service on failures, which
makes a relatively good self-healing solution without pacemaker.

See systemd.service(5) for details on Restart=

Note that the fetch_name_from_service_resource attribute of this
resource enables automatically fetching the systemd service name from
the service resource, which helps remove duplication of code in the
cookbooks when the service name is being overridden in the attributes of
the service resource. For instance, this will work as expected:
```
  service "foobar" do
    service_name "notfoobar"
  end

  utils_systemd_service_restart "foobar"
```

### CODE REVIEW

**Comment by aplanas** [comment]
I would prefer to consider it a bug in the package. In this way will be beneficial for Ardana, raw openSUSE packages and any alternative method of deployment

**Comment by vuntz** [comment]
> I would prefer to consider it a bug in the package. In this way will be beneficial for Ardana, raw openSUSE packages and any alternative method of deployment

Good point. I'll defer to @aspiers on how it should be handled; he may have given this some thoughts, and I don't have a strong feeling.

(note however that I'd need a backport to stable/4.0, where we can't change this in the service files)

**Comment by aspiers** [comment]
If we put this in the packages then we'd have to disable it again for the (default) case where Pacemaker is managing the services.  Is that even doable?  If we need the packages to support both approaches, my hunch is that it's going to be easier if they are kept less opinionated, i.e. the restart is layered on top like it is here (and could easily be done in Ardana too in a similar way).

**Comment by aplanas** [comment]
@aspiers in this case we need to coordinate with the packages:

```
rpm-packaging> grep -R 'Restart' * | wc -l
38
```

**Comment by vuntz** [comment]
> If we put this in the packages then we'd have to disable it again for the (default) case where Pacemaker is managing the services. Is that even doable? If we need the packages to support both approaches, my hunch is that it's going to be easier if they are kept less opinionated, i.e. the restart is layered on top like it is here (and could easily be done in Ardana too in a similar way).

I updated the pull request to actually allow anything in the package: if we call `:disable` on the resource, then it will create a config snippet with `Restart=no` and if we call `:enable`, it will create a config snippet with `Restart=on-failure` (or some other value, depending on the attributes).

How does that sound?

**Comment by aplanas** [comment]
@vuntz If this works with Pacemaker, I think IMHO that is a great solution.

**Pull request merged**
