### PR TITLE
Return true if repos are present (or not needed)

### PR DESCRIPTION
**Pull request by jsuchome**
cc @rsalevsky @rhafer

### CODE REVIEW

**Comment by jsuchome** [comment]
I'm not sure if 2nd commit is correct way to do it. However, it also should not be right to require user to **Recheck** when everything is already correctly in place.

**Comment by rsalevsky** [comment]
@jsuchome I would say we should postpone the second commit. There was no decision yet if we should skip steps or just say that everything is fine.

**Comment by jsuchome** [comment]
Well, either way, currently the page does not say "that everything is fine", but tells me that HA repos are missing.

**Comment by rsalevsky** [comment]
Let's just merge the first commit and I will implement something for the second.

**Comment by jsuchome** [comment]
OK, deleted https://github.com/jsuchome/crowbar-core/commit/8986c79efee52b0e6fb27e26fca0e5091421df2c

**Comment by rhafer** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Pull request merged**
