### PR TITLE
crowbar-hack: be sure that UEFI is there.

### PR DESCRIPTION
**Pull request by aplanas**
Fix bnc#976048

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Comment by tboerger** [comment]
:+1:

**Comment by rsalevsky** [comment]
There are some hound issues which can be fixed also please rebase to get my last changes to the hound configs.

**Comment by aplanas** [comment]
* Rebased and removed most of the Hound complains

@rsalevsky r?

**Comment by dguitarbite** [comment]
IMO, the nodes are timing out during the ``setupnodes`` part in the CI system. Since this change is related to UEFI boot, it looks suspiciously related to the code changes. Although I am not sure if its the issue from the mkcloud hardware (does not look like it since the CI job was waiting for 13~ minutes before failing), but I strongly believe its due to the given changes in this PR. If you wish me to dig deeper into the same, feel free to ping me.

**Comment by rsalevsky** [comment]
Are there long versions of the commands for the `efibootmgr`? If yes we should use them to make the code easier to read.

**Comment by aplanas** [comment]
* Use long parameters for `efibootmgr`

**Comment by rsalevsky** [comment]
Locks good now, let's wait for the gating.

**Comment by aplanas** [comment]
Gating is gree

**Comment by rsalevsky** [comment]
+1

**Comment by nicolasbock** [comment]
+1

**Pull request merged**
