### PR TITLE
ipmi, provisioner: Fix migrations for new roles

### PR DESCRIPTION
**Pull request by vuntz**
We also need to update the node roles for nodes that are using these
roles.

### CODE REVIEW

**Comment by jsuchome** [comment]
+1 after testing

**Comment by rsalevsky** [comment]
The gating failure looks related.

**Comment by vuntz** [comment]
@rsalevsky we also need the patch from https://github.com/crowbar/crowbar-core/pull/561, so we're doing a combined gating there.

**Comment by vuntz** [comment]
Patch was merged as part of https://github.com/crowbar/crowbar-core/pull/561

**Pull request closed without merging**
