### PR TITLE
Fixes to avoid issues with discovery image

### PR DESCRIPTION
**Pull request by vuntz**

### CODE REVIEW

**Comment by vuntz** [comment]
It's unfortunately still not enough, but it does help a bit and this makes sense anyway imho, so removing the WIP tag.

**Comment by rhafer** [comment]
+1

**Comment by jsuchome** [comment]
+1

**Comment by aplanas** [comment]
No idea about this command, but looks like that also there is this version: `ifcfg=*=dhcp4` or `ifcfg=eth*=dhcp4`. Not sure if one of the previous can be more accurate for this solution.

**Comment by vuntz** [comment]
@aplanas I don't know either, I just copied what we use in the update_nodes recipe :-)

**Pull request merged**
