### PR TITLE
enhance network check specs

### PR DESCRIPTION
**Pull request by MaximilianMeister**

### CODE REVIEW

**Comment by tboerger** [comment]
Cool
:+1:

**Comment by tboerger** [comment]
> This branch is out-of-date with the base branch

**Comment by MaximilianMeister** [comment]
rebased

**Comment by rsalevsky** [comment]
+1

**Comment by MaximilianMeister** [comment]
still the same gating error with cct-manila, highly unlikely that this was caused by editing a spec

**Pull request merged**
