### PR TITLE
Only load crowbar-init in production

### PR DESCRIPTION
**Pull request by rsalevsky**
We can't load crowbar-init in the development env via a Gemfile.

### CODE REVIEW

**Comment by abel-navarro** [comment]
why only load crowbar-init in production?
who set `Rails.env.production`?

**Comment by rsalevsky** [comment]
@abel-navarro We can't load crowbar-init in development because of the Gemfile restrictions. If we use a Gemfile bundle expect also deps for crowbar-init in the crowbar Gemfile but this is not the case so the loading of crowbar-init fails.

It's rails build in: http://api.rubyonrails.org/classes/Rails.html#method-c-env

**Comment by MaximilianMeister** [comment]
> We can't load crowbar-init in development because of the Gemfile restrictions. If we use a Gemfile bundle expect also deps for crowbar-init in the crowbar Gemfile but this is not the case so the loading of crowbar-init fails.

would be good to have that in the commit message

**Comment by rsalevsky** [comment]
@MaximilianMeister Updated the commit message.

**Pull request merged**
