### PR TITLE
provisioner: Fix list of DNS servers hinted by DHCP

### PR DESCRIPTION
**Pull request by vuntz**
We were hardcoding the admin IP address there.
But we want to allow people to host the DNS server on other nodes than the admin-node.

### CODE REVIEW

**Comment by bmwiedemann** [comment]
Not sure, what problem you are trying to fix here, but as far as I understood, DHCP is only used in discovery and autoyast install stages, where using the admin IP as DNS is the most appropriate (e.g. because it allows reverse lookups of IP when you ssh into a discovered system)... and HA is not a concern, because they cannot do anything without the admin node anyway.

**Comment by vuntz** [comment]
@bmwiedemann right now, it's possible to run a cloud where the admin server is not the dns server. You can deploy one node, move the dns-server role there, then discover other nodes (some people do that, yes).

This is what this would be fixing.

**Comment by bmwiedemann** [comment]
I think, there might be other problems, because we trigger a chef-client run on the admin-node for certain DNS/DHCP changes to happen.
And did we implement moving or uninstalling services yet?

**Comment by vuntz** [comment]
@bmwiedemann I'm not claiming it's fixing the full thing, just that at least the config file is reflecting the reality. Is there an issue with this change?

**Comment by bmwiedemann** [comment]
+1  (was just making sure to understand why we are doing the change - a question that should ideally be answered by the commit message)

**Comment by nicolasbock** [comment]
+1

**Pull request merged**
