### PR TITLE
network: Don't specify which flavor of openvswitch kmp to install

### PR DESCRIPTION
**Pull request by vuntz**
Let zypper install the right one automatically.

### CODE REVIEW

**Comment by aplanas** [comment]
+1

**Comment by tboerger** [comment]
:+1:

**Comment by rhafer** [comment]
@vuntz Does it really work with Xen? I was wondering if the right kmp actually is installed before the node is rebooting. Or does installing the xen kernel also pull in the ovs kmp?

**Comment by vuntz** [comment]
@rhafer I triggered a new gating job with xen, so let's see what happens. You're right that the xen kmp will only be installed on the reboot, but this might still be okay (hopefully ovs fails to start, but chef-client will start it).

**Comment by vuntz** [comment]
Obsoleted by https://github.com/crowbar/crowbar-core/pull/517

**Pull request closed without merging**
