### PR TITLE
use public-foo hostnames (bsc#1110080)

### PR DESCRIPTION
**Pull request by bmwiedemann**
to be covered by CA certificate wildcards

e.g. *.p3.cloud.suse.de
does not cover public.cluster-services.p3.cloud.suse.de.
but it does public-cluster-services.p3.cloud.suse.de.

Please help potential reviewers to understand this pull request and speed
up the process by writing a meaningful pull request message.

Answering the following questions can help, but is optional.

**Why is this change necessary?**
To make it easier to use SSL with wildcard CA certificates

**How does it address the issue?**
by not introducing a subdomain level, which is not covered by SSL cert wildcards

**Is there additional information worth sharing like links to a Trello
card, bug references, testing advice or dependencies to other pull
requests?**
with public- in names it is possible to collide with node aliases that also get written to DNS

### CODE REVIEW

**Comment by vmoravec** [comment]
The proposed change conflicts with the proposal for cluster domain naming scheme in our docs, see chapter 11.1 for SOC7

**Comment by bmwiedemann** [comment]
So we would have to update the documentation accordingly when this gets merged.

**Comment by bmwiedemann** [comment]
[doc bug](https://bugzilla.suse.com/show_bug.cgi?id=1110080) filed

**Comment by bmwiedemann** [comment]
https://github.com/bmwiedemann/crowbar-core/tree/publicname also has it added to the commit message, but I cannot edit the PR to take it as source.

**Pull request merged**
