### PR TITLE
[4.0] upgrade: Remove database step from the list of 7-8 upgrade steps

### PR DESCRIPTION
**Pull request by jsuchome**
During 7 to 8 upgrade, crowbar database does not need to be changed. Partial port of 
https://github.com/crowbar/crowbar-core/pull/1586

### CODE REVIEW

**Comment by skazi0** [comment]
Couldn't this be cherry-picked from https://github.com/crowbar/crowbar-core/pull/1586 ?

**Comment by jsuchome** [comment]
Probably yes. But that PR contains more so I think it's fine to leave it separate

**Comment by skazi0** [comment]
That PR has multiple commits, one of them seems to match this one. If you don't want to cherry pick, please mention "partial backport" in PR description at least.

**Comment by jsuchome** [comment]
@skazi0 adapted the description

**Comment by nicolasbock** [comment]
Maybe even better if you mention the one commit you included in here for reference also.

**Comment by jsuchome** [comment]
@nicolasbock I've updated the commit message

**Pull request merged**
