### PR TITLE
Refactor routes part 2

### PR DESCRIPTION
**Pull request by rsalevsky**

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
change looks good, and gating is also green

+1

**Comment by nicolasbock** [comment]
+1

**Comment by vuntz** [comment]
@rsalevsky did you check that no other `crowbar-*` repo is using any of the renamed methods, btw?

**Comment by rsalevsky** [comment]
@vuntz Yes, checked all repositories.

**Comment by MaximilianMeister** [comment]
same here

https://github.com/crowbar/crowbar-core/pull/532#issuecomment-230419080

wasn't there problems when merging all changes at once?

**Pull request merged**
