### PR TITLE
Revert "batch build: abort on unknown aliases" (bsc#944404)

### PR DESCRIPTION
**Pull request by toabctl**
This reverts commit 2b351ca757aac468497198baf97f98d5138bd8cb.

### CODE REVIEW

**Comment by aspiers** [comment]
Why?

**Comment by toabctl** [comment]
> Why?

See bug report.

**Comment by toabctl** [comment]
@thutterer maybe you want to have a look?

**Comment by aspiers** [comment]
-1, we can fix this properly simply by reintroducing `ALIAS_REGEXP`.  It was dropped by 5849ca5917621436 since we didn't reuse it, and I guess 2b351ca was written before that but merged after it appeared, causing the breakage.

BTW best practice is to include the full bugzilla URL inside the commit message as explained at https://etherpad.nue.suse.com/p/cloud-pull-requests

**Comment by dirkmueller** [comment]
I disagree with the requirement to include full bugzilla urls btw..

**Comment by aspiers** [comment]
I didn't say it was a requirement, and nor does the etherpad.  However the advantages of giving the full URL are very obvious (and also explained in the etherpad), which is why I said it's best practice.  If you have arguments against this, please provide them.  And BTW "pasting a URL into a commit message is an extra 3 seconds of work" is not a valid argument ;-)

**Comment by aspiers** [comment]
Closing as it's just as easy to reintroduce the missing constant, and that will avoid having to ditch the valuable sanity check introduced by 2b351ca.

**Comment by toabctl** [comment]
@aspiers are you going to fix this then? ```crowbar_batch``` is unusable for now.

**Comment by aspiers** [comment]
It's a one-line fix to add the constant, but OK I can do it if you want.

**Pull request closed without merging**
