### PR TITLE
network: override sysctl netfilter disable parameter (SOC-6229)

### PR DESCRIPTION
**Pull request by sandonovsuse**
SLES12 comes with sysctl net.bridge.bridge-nf-call-iptables
parameter set to zero, thus disabling netfilter on bridges on each
sysctl --system execution.

This patch overrides net.bridge.bridge-nf-call-iptables = 0 found in
sysctl.d/50-default.conf by creating a file 51-bridge-netfilter.conf,
setting the netfilter parameter to 1. (SOC-6229)

### CODE REVIEW

**Comment by sandonovsuse** [comment]
Agreed, although I was trying to avoid possibly long discussion on how the change might affect products other than cloud - given that the bug is already in customer production. Personally, I would rather have this reach the MU quickly, and chase the aaa_base change in peace, even though it's double the effort. Also, happy to close the PR if you prefer otherwise?

**Comment by rhafer** [comment]
>  Also, happy to close the PR if you prefer otherwise?

No. It's fine. I was just wondering if we're going to drop the ball on the aaa_base change (again).

**Comment by sandonovsuse** [comment]
>@@sandonovsuse sandonovsuse force-pushed the sandonovsuse:override-sysctl-netfilter-disable-parameter-SOC-6229 branch from 8cefcff to 54e8405 

Commit title changed to match convention. Required by ci/cd

**Comment by s-t-e-v-e-n-k** [comment]
That has been merged to master, rebase.

**Pull request merged**
