### PR TITLE
Adding the functionality to search and replace a line

### PR DESCRIPTION
**Pull request by ovisan**
The search is done with regex expressions and the replacement is string

### CODE REVIEW

**Comment by aspiers** [comment]
Nice idea!  I wonder why Chef doesn't provide this by default.  Maybe [the recommended way is to always use templates](http://stackoverflow.com/questions/14848110/how-i-can-change-a-file-with-chef), but I think there are genuine scenarios where search+replace is a valid approach.

Having said that, I wonder if this really belongs in the existing `line` LWRP, since it will potentially modify multiple lines.  And also I have to give -1 for now, since you just added a merge commit to the PR.  PRs should not have merge commits.

**Comment by ovisan** [comment]
@aspiers fixed the merge commit. Right, i was also looking at the recommended way using templates and i agree that should be done for a broader scenario. In this case we just want to modify a line or a specific text matched by a regular expression.

**Comment by tboerger** [comment]
:+1:

**Comment by ovisan** [comment]
Seems search_file_replace_line exists and it's working, closing the PR.

**Pull request closed without merging**
