### PR TITLE
re-add the target_platform cleanup

### PR DESCRIPTION
**Pull request by MaximilianMeister**
this must have been accidentally removed

### CODE REVIEW

**Comment by jsuchome** [comment]
spec need to update for that NodeObject search

**Comment by MaximilianMeister** [comment]
> spec need to update for that NodeObject search

done

**Comment by MaximilianMeister** [comment]
rebased. gating was stuck in testbuild

**Comment by vuntz** [comment]
@MaximilianMeister can you rebase?

**Comment by jsuchome** [comment]
Oh. I think we do not need this any more, it got obsoleted by https://github.com/crowbar/crowbar/commit/6e937d51ab8b610bac861cb8c02126fba483adda

**Comment by rsalevsky** [comment]
@MaximilianMeister Can you rebase or close it?

**Comment by jsuchome** [comment]
Let's close it, it's not needed

**Pull request closed without merging**
