### PR TITLE
use exception_notification to log all exceptions in the database

### PR DESCRIPTION
**Pull request by MaximilianMeister**
this would be using the Api::Error model to write any exception
into the database.
collecting all exceptions in a single place saves the time to crawl
through the logs.

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;kXfs4mJk&#x2F;109-log-all-exceptions-with-exception-notification-gem"> log all exceptions with exception_notification gem</a>

**Comment by aspiers** [comment]
I'm not necessarily against this *in principle*, but please can you make the commit message say more about the exact use case(s) you expect this to be used for? There are potential downsides, e.g. bloating of the database, the need for extra cleanup of old exceptions, so it should be made clear why the upsides outweigh the downsides.

**Comment by MaximilianMeister** [comment]
> can you make the commit message say more about the exact use case(s) you expect this to be used for?

I don't think that there is any other use case than looking up errors that happened during runtime. I didn't think about any cleanups yet, at least not automatically on a regular base.

This is also just one step, the more dynamic one which just writes all exceptions automatically. The other steps would be to write errors to that table when we fill an errors Hash in a model e.g., or just manually in the code at some critical points.

the original Idea about collecting errors in one place came from @kwwii IIRC, and it was really only about a one stop for all errors (which is still some way to go)

**Comment by MaximilianMeister** [comment]
closing for now, as it's not really needed at this point in time

**Pull request closed without merging**
