### PR TITLE
Upgrade to bootstrap 3.4.1 (SCRD-7470)

### PR DESCRIPTION
**Pull request by eapodaca**
Upgrade to bootstrap 3.4.1 to address XSS vulnerability

### CODE REVIEW

**Comment by jeremy-moffitt** [comment]
http://suserose.us.to:1338/  has been updated to include this change, I've also reached out to @gosipyan and @kbaikov for guidance on creating a build with this as part of it for testing

**Comment by skazi0** [comment]
Main question: do we just want to upgrade to new bootstrap to fix the xss problem (and keep the overall look and feel) or do we want to switch to new bootstrap "style"?

I see lots of visual changes at http://suserose.us.to:1338

**Comment by skazi0** [comment]
Second question: do we plan/need to support Firefox (or other browsers maybe) besides Chrome. Currently in Firefox it the style is completely broken.

**Comment by jeremy-moffitt** [comment]
> Second question: do we plan/need to support Firefox (or other browsers maybe) besides Chrome. Currently in Firefox it the style is completely broken.

If its broken in Firefox and was not before, then thats a problem we need to fix

**Comment by jeremy-moffitt** [comment]
> Main question: do we just want to upgrade to new bootstrap to fix the xss problem (and keep the overall look and feel) or do we want to switch to new bootstrap "style"?
> 
> I see lots of visual changes at http://suserose.us.to:1338

that system also has color and font changes for branding (see: https://build.suse.de/request/show/185097 )

**Comment by eapodaca** [comment]
@skazi0 what do toy mean by "completely broken" it looks mostly ok for us on FF 65.
screenshot from 2019-02-28 09-55-08

**Comment by Itxaka** [comment]
Some issues:

Cancel button is gigantic for some weird reason :rofl: 

img


Items in the barclamp list are waaaay to close to each other, making difficult to click on them (on the node view)

img2


On creating a backup, the creation button is way too close to the window border

img3


All of the above on Firefox 65 64-bit Linux.

On Chrome 72.0.3626.119 64-bit linux, the only thing that is fixed is the cancel button size, the other 2 are the same.

**Comment by eapodaca** [comment]
@Itxaka Good catch, I've addressed those issues.

**Comment by skazi0** [comment]
@eapodaca even on your screenshot:
- [ ] http://suserose.us.to:1338/crowbar/modules/1.0 big edit buttons (compared to create)
Others I spotted (probably not all):
- [ ] http://suserose.us.to:1338/nodes/crowbar big edit button
- [ ] http://suserose.us.to:1338/nodes/crowbar/edit big cancel button
- [ ] http://suserose.us.to:1338/nodes/list big show unallocated button
- [ ] http://suserose.us.to:1338/crowbar/modules/1.0 the texts are not centered vertically (same as in chrome)
- [ ] http://suserose.us.to:1338/crowbar/dns/1.0/proposals/default big Add/Remove buttons
- [ ] http://suserose.us.to:1338/crowbar/nfs_client/1.0/proposals/proposal_1 big Add button
- [ ] http://suserose.us.to:1338/crowbar/pacemaker/1.0/proposals/proposal_1 the "Ring" headers are huge (and green) and you can't see the button there
- [ ] http://suserose.us.to:1338/crowbar/rabbitmq/1.0/proposals/default big Add button
- [ ] http://suserose.us.to:1338/crowbar/cinder/1.0/proposals/default huge green headers for backends
- [ ] http://suserose.us.to:1338/crowbar/manila/1.0/proposals/default green headers again

- [ ] the black highlight on the top menu bar is not very visible
- [ ] (opinion) too much spacing between top menu and start of main content
- [ ] (opinion) too little spacing inside content, e.g. http://suserose.us.to:1338/crowbar/suse_manager_client/1.0/proposals/default (blue box)

**Comment by eapodaca** [comment]
@skazi0 Addressed most items.

> (opinion) too much spacing between top menu and start of main content

This is set in the global.scss file and is not a part of this change

> (opinion) too little spacing inside content, e.g. http://suserose.us.to:1338/crowbar/suse_manager_client/1.0/proposals/default (blue box)

This has gotten a little better not sure its enough though

**Comment by skazi0** [comment]
@eapodaca one more: some buttons have text with weight 400 while most have weight 700 (bold) e.g. http://suserose.us.to:1338/nodes/list or http://suserose.us.to:1338/crowbar/pacemaker/1.0/proposals/proposal_1 . In old version all (?) buttons had weight 400. Please clarify this and make the style consistent.

**Comment by eapodaca** [comment]
@skazi0 I've standardized on font weight 700, as recommended by the design standard. but really all these changes are not related to this bootstrap upgrade PR. !1806 is where all the look-feel changes are made.

**Comment by skazi0** [comment]
@eapodaca thx for the info. I didn't know about the other PR.

**Comment by jeremy-moffitt** [comment]
@rsalevsky since you reviewed the other PR associated with branding, if you have a chance please look at this one too... it looks like a lot of files, but its basically replacing the bootstrap files which are checked into the vendor folder... the slew of hound messages from the original checkin was before the hound ignore rules were updated to exclude the vendor folder since we have no meaningful way of fixing those

**Comment by skazi0** [comment]
@jeremy-moffitt is it currently applied somewhere? `suserose.us.to` seems to be back to the old style.

**Comment by jeremy-moffitt** [comment]
@skazi0 that would be the only place unless @eapodaca forwarded it via a different port for his rebuild... I'll reach out to him and see if we can verify the status, sorry about that!

**Comment by papodaca** [comment]
I've got this patched with the current upgrade and look and feel patches. There is still an issue related to glyphicons that I have yet to figure out.

**Comment by jeremy-moffitt** [comment]
@skazi0 @rsalevsky  I just talked to @eapodaca and he tells me the glyphicons issue is fixed in the latest rev that he force pushed 5 days ago. Please review this and https://github.com/crowbar/crowbar-core/pull/1806  when you have a chance so we can get this across the finish line. Let us know if you run into any isues, thanks!

**Pull request merged**
