### PR TITLE
Address review comments for Autoyast upgrade

### PR DESCRIPTION
**Pull request by rhafer**
This PR addresses most of the concerns raised in https://github.com/crowbar/crowbar-core/pull/137

https://github.com/crowbar/crowbar-core/pull/137#discussion_r49742668 (error handling for nodes failing to reboot is not yet solved and needs further debugging I am tracking that one in trello)

### CODE REVIEW

**Comment by vuntz** [comment]
Thanks a lot, +1.

**Comment by rhafer** [comment]
Updated with one change that I overlooked :/

**Comment by vuntz** [comment]
Still +1

**Comment by mmnelemane** [comment]
+1

**Comment by aplanas** [comment]
+1

**Pull request merged**
