### PR TITLE
webui: Fix compatibility issues with recent jquery (bsc#949926)

### PR DESCRIPTION
**Pull request by vuntz**
jquery expects the namespace to be a string, not an array.

https://bugzilla.suse.com/show_bug.cgi?id=949926

### CODE REVIEW

**Comment by toabctl** [comment]
the commit message for the 2nd commit could be a bit more detailed ;) Mention at least that it's ui releated

**Comment by vuntz** [comment]
> the commit message for the 2nd commit could be a bit more detailed ;) Mention at least that it's ui releated

It's because the commit is probably wrong, and I'm just guessing what could possibly fix it. But that doesn't work yet...

**Comment by tboerger** [comment]
And why did you switch from slashes to dots?

**Comment by tboerger** [comment]
I have not tested the events part but as you have tested that I'm fine with it.

**Comment by vuntz** [comment]
> And why did you switch from slashes to dots?

Because it seems that's what jquery uses internally.

> I have not tested the events part but as you have tested that I'm fine with it.

It's not working, so help welcome :-) I am really just a monkey editing a text file for this one.

**Comment by tboerger** [comment]
> Because it seems that's what jquery uses internally.

But https://github.com/crowbar/crowbar-core/pull/74/files#diff-609454585c3fcff9fb49122cdf32a93aR48 got nothing to do with jquery internals?

**Comment by vuntz** [comment]
@tboerger and the commit is titled "More random changes". And I truly mean "random", because I don't know this stuff; just trying to get to a state that works until someone who has knowledge fixes it.

**Comment by tboerger** [comment]
> It's not working, so help welcome :-) I am really just a monkey editing a text file for this one.

When my installation is done I will look into that. So pacemaker and neutron dynamic forms are currently broken?

**Comment by vuntz** [comment]
@tboerger yes, see the bug.

**Comment by tboerger** [comment]
Replaced by https://github.com/crowbar/crowbar-core/pull/77 and https://github.com/crowbar/crowbar-ha/pull/31

**Pull request closed without merging**
