### PR TITLE
webui: Hide some steps in the installer

### PR DESCRIPTION
**Pull request by vuntz**
Some steps make no sense to display, so just group them together.

cc @MaximilianMeister @kwwii

### CODE REVIEW

**Comment by vuntz** [comment]
Ken was mentioning that we could possibly merge the remaining first two as "Starting up" and change the last one as "Finishing...".

**Comment by rsalevsky** [comment]
I was thinking about making the steps anyway more dynamic and sending them in the json instead of define them in the view. This can be useful for the backup-restore case as well as for other distros

**Comment by tboerger** [comment]
I would prefer more steps to show more progress if it can be updated frequently enough.

**Comment by vuntz** [comment]
> I would prefer more steps to show more progress if it can be updated frequently enough.

For more steps, the user can just look at the log directly. I don't think it makes the UI clearer to have more steps.

**Comment by tboerger** [comment]
As the SE on our last meeting said... It makes the users happier to see progress ;)

**Comment by vuntz** [comment]
Won't be used...

**Pull request closed without merging**
