### PR TITLE
provisioner: Remove one level of indentation in update_nodes recipe

### PR DESCRIPTION
**Pull request by vuntz**
There's an "if" test which is useless.

This looks big, but use https://github.com/crowbar/crowbar-core/pull/949/files?w=1 to review. Also, there are many hound comments (which are valid), but they are actually not introduced by this change and I didn't want to fix all of them as this would make things less reviewable.

### CODE REVIEW

**Comment by vuntz** [comment]
For the record, I'm not going to fix the other hound violations here: they weren't introduced by the change and I'm not agreeing these should be fixed.

**Comment by nicolasbock** [comment]
@vuntz The trick with appending `?w=1` is very neat! Where did you find it? I have been trying to find a UI option that would turn this on but so far haven't found it.

**Comment by vuntz** [comment]
> @vuntz The trick with appending ?w=1 is very neat! Where did you find it?

It's probably one of the first thing I looked for when doing reviews in github ;-) So no idea how I found it as it's been a long time for me using it...

**Comment by nicolasbock** [comment]
@vuntz Thanks for sharing :)

**Comment by aspiers** [comment]
@nicolasbock @vuntz There's also https://github.com/jerone/UserScripts/tree/master/Github_Commit_Whitespace which is a more convenient version of the same. I recommend you (re-)read my [September post to `research@`](http://mailman.suse.de/mlarch/SuSE/research/2016/research.2016.09/msg00301.html) :-)

**Pull request merged**
