### PR TITLE
3.0 | Switch app name and page name in title (bsc#967423)

### PR DESCRIPTION
**Pull request by rsalevsky**
(cherry picked from commit f28764b5dabb5d912f701605338d4072804da0ce)

### CODE REVIEW

**Comment by vuntz** [comment]
+1

**Comment by MaximilianMeister** [comment]
+1 ....the PR title fits to the change here :-)

**Comment by tboerger** [comment]
:+1:

**Comment by vuntz** [comment]
Gating failure in tempest, unrelated to this PR.

**Pull request merged**
