### PR TITLE
Do not create a postgresql db dump when upgrading

### PR DESCRIPTION
**Pull request by rhafer**
It's not needed currently. Note: This commit just removes the chef part of the
database dump. It's just enough to make the upgrade work again. The crowbar
side (i.e. the steps in the upgrade wizard) is not changed.

### CODE REVIEW

**Comment by aplanas** [comment]
Is crowbar also doing a dump somewhere else?

+1 if this is the case

**Comment by jsuchome** [comment]
+1

**Comment by rsalevsky** [comment]
@jsuchome Didn't we said the we want to dump the database and store it the admin node in case something goes wrong? At least this is what we discussed with the design team and what they plan for the UI.

**Comment by sayalilunkad** [comment]
I also think it's a good idea to keep the dump in case something goes wrong.

**Comment by jsuchome** [comment]
@rsalevsky hm, it's true we have OpenStack database backup in our notes and mentioned in the angular wiki. @rhafer maybe we can still keep the dump and just remove automatic restore from the dump?

**Comment by rhafer** [comment]
> hm, it's true we have OpenStack database backup in our notes and mentioned in the angular wiki.

But wouldn't that database backup implementation look completely different to what's implemented in the old upgrade procedure?

> maybe we can still keep the dump and just remove automatic restore from the dump?

Well, https://github.com/crowbar/crowbar-openstack/pull/495 should work without this change here. I just thought leaving that code lying around basically unused it probably a bad idea.

**Comment by jsuchome** [comment]
> But wouldn't that database backup implementation look completely different to what's
> implemented in the old upgrade procedure?

Maybe, maybe not. So far, I still think we have to use chef recipes to access the clients, so the database dump might look pretty similar.

> Well, crowbar/crowbar-openstack#495 should work without this change here. 

That's what I meant.

**Comment by rhafer** [comment]
> Maybe, maybe not. So far, I still think we have to use chef recipes to access the clients, so the database dump might look pretty similar.

If you want to dump to the admin node as @rsalevsky suggested it might make more sense to just  to that via RemoteNode.ssh_cmd (https://github.com/crowbar/crowbar-core/blob/master/crowbar_framework/lib/remote_node.rb#L82). But anyway, feel free to close this if you don't need it. The other PR should be enough to fix the immediate issue.

**Comment by jsuchome** [comment]
Yes, ssh commands might be our option, that's true.

**Comment by rsalevsky** [comment]
As Ralf already said in the other PR it's git so we can restore the change whenever we want. So let's merge the PR for now and add it as reference to the card where we do the actual implementation for the OpenStack DB dump.

+1

**Comment by rhafer** [comment]
@jsuchome  Do you agree with @rsalevsky 's last comment, or would you prefer to close this?

**Comment by jsuchome** [comment]
I agree with Rick, yes. Sorry if it caused delay.
+1

**Comment by rhafer** [comment]
> Sorry if it caused delay.

Don't worry. It didn't cause any delay. (The other PR was the more important part)

**Pull request merged**
