### PR TITLE
Update default look and feel to use eos colors

### PR DESCRIPTION
**Pull request by eapodaca**
Updates bootstrap variables to use eos colors and Lato font.

### CODE REVIEW

**Comment by skazi0** [comment]
Is there some env where both this PR and #1797 can be seen together?

**Comment by jeremy-moffitt** [comment]
I believe http://suserose.us.to:1338  has both of these changes, @eapodaca can confirm

**Comment by eapodaca** [comment]
Attempted to port these changes to that system. Ended up I have to rebuild it.

**Comment by jeremy-moffitt** [comment]
@eapodaca looks like its back up and running? @skazi0 please take a look when you have a chance. Thank you!

**Comment by jeremy-moffitt** [comment]
wondering if this needs to be rebased, though the build error is a bit cryptic, I'm guessing its having trouble patching vendor.scss
```
13:48:14 [  347s] patching file crowbar_framework/vendor/assets/stylesheets/vendor.scss
13:48:14 [  347s] error: Bad exit status from /var/tmp/rpm-tmp.goxnWN (%prep)
13:48:14 [  347s] 
13:48:14 [  347s] 
13:48:14 [  347s] RPM build errors:
13:48:14 [  347s]     Bad exit status from /var/tmp/rpm-tmp.goxnWN (%prep)
13:48:14 [  347s] 
13:48:14 [  347s] p1testbuild.openstack.local failed "build crowbar-core.spec" at Thu Mar  7 20:48:14 UTC 2019.
13:48:14 [  347s] 
13:48:14 
13:48:14 The buildroot was: /tmp/d20190307-27941-1hgfaz9/crowbar-core/BUILD
13:48:16 unknown error - Build failed.```

**Comment by rsalevsky** [comment]
Testbuild will not work for this change as it includes binary changes.

**Comment by jeremy-moffitt** [comment]
@skazi0 any chance you could take another look at this this week? would be great to get this and #1797  in this week so they could be in RC5 (though 1797 needs two reviewers, maybe I'll ping Rick :))

**Comment by skazi0** [comment]
@eapadoca is the latest version of this also applied to http://suserose.us.to:1338 ?

**Comment by eapodaca** [comment]
@skazi0 yes that box is up to date with these changes.

**Comment by skazi0** [comment]
Some more comments:
- [ ] the raw proposal view has rounded corners - http://suserose.us.to:1338/crowbar/crowbar/1.0/proposals/default?attr_raw=true
- [ ] Show unallocated -> not bold - http://suserose.us.to:1338/nodes/list
- [ ] unsure: shall we change the green color for "LEDs" that are used in various places? (e.g. next to sw-unknown on the dashboard)
- [ ] Create/Upload Backup Image -> not bold - http://suserose.us.to:1338/utils/backups
- [ ] Browse button in Upload Backup Image modal is a bit higher than the text input
- [ ] After backup file is selected, Remove, Upload, Browse and text input are not aligned correctly
- [ ] New export -> not bold - http://suserose.us.to:1338/utils

**Comment by skazi0** [comment]
@eapodaca there seems to be some rebase problem in this PR... I see some of @jsuchome's commits which should probably not be here

**Comment by jeremy-moffitt** [comment]
@eapodaca does the latest force-push cover both the rebase and @skazi0 's latest review?

**Comment by eapodaca** [comment]
@jeremy-moffitt That push contained a rebase only to remove the commits that snuck in somehow. Still working on a few of those items.

**Comment by eapodaca** [comment]
>   the raw proposal view has rounded corners

@skazi0 This is set in the CodeMirror.scss file. Its possible I've removed a more specific selector that was suppressing that. Its not clear to me, but looks intentional in that file. It is a reasonable change we can make if its needed in your view (I've made that change on the crowbar box).

**Comment by skazi0** [comment]
@eapodaca regarding the rounding of raw views I don't mind either way. I was looking for things which looked inconsistent. Since we remove a lot of rounding with this change this caught my attention.

**Comment by rsalevsky** [comment]
Needs a rebase.

**Comment by eapodaca** [comment]
Rebased this on master.

**Comment by jeremy-moffitt** [comment]
@skazi0  @rsalevsky  Ethan rebased this and cleared out the previous reviews. Please take another look if either/both of you have time. Thank you so much! Almost there :)

**Pull request merged**
