### PR TITLE
upgrade: Added basic time stamps to the scripts executed by upgrade

### PR DESCRIPTION
**Pull request by jsuchome**
The output of the scripts looks like this: http://pastebin.nue.suse.com/18770/src

### CODE REVIEW

**Comment by jsuchome** [comment]
[Print time stamps while logging from upgrade scripts (into /var/log/crowbar/node-upgrade.log)](https://trello.com/c/8HItaUt6/240-print-time-stamps-while-logging-from-upgrade-scripts-into-var-log-crowbar-node-upgrade-log)

**Comment by MaximilianMeister** [comment]
what about replacing all echos with a log function that always logs a timestamp as well?

**Comment by jsuchome** [comment]
@mmnelemane sounds good

**Comment by jsuchome** [comment]
I know, some library would be good for it... I just did not want to think how should it be done and where should it belong...

**Comment by rsalevsky** [comment]
Needs a rebase

**Pull request merged**
