### PR TITLE
create tarball with root, drop archive gem

### PR DESCRIPTION
**Pull request by MaximilianMeister**

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
I assume we don't need archive anymore? can anyone confirm?

**Comment by rhafer** [comment]
> I assume we don't need archive anymore? can anyone confirm?

@rsalevsky  It was introduced only for the backup restore feature, right ? If yes, it can go now.

**Comment by rsalevsky** [comment]
Yes, was just for this usecase.

**Comment by MaximilianMeister** [comment]
> Yes, was just for this usecase.

we will probably have to remove it from the product as well then

**Comment by rhafer** [comment]
+1

**Comment by rsalevsky** [comment]
+1

**Pull request merged**
