### PR TITLE
[3.0] Use repository key fingerprints for verification (bsc#988907)

### PR DESCRIPTION
**Pull request by nicolasbock**

### CODE REVIEW

**Comment by vuntz** [comment]
Can you use `cherry-pick -x`?

**Comment by nicolasbock** [comment]
@vuntz Is it ok if the cherry-pick copies cloud 7 repository information?

**Comment by vuntz** [comment]
Ah, yeah, hrm, maybe mention the other commit even if it's not a cherry-pick then. The key point is that we want to have the link to the change in master.

**Comment by vuntz** [comment]
+1, but gating is red.

**Comment by nicolasbock** [comment]
Gating fails in `testsetup` in manila tests, i.e. past the point during which this piece of code is used.

**Comment by aspiers** [comment]
+1

**Pull request merged**
