### PR TITLE
[stable/3.0] Make ceph cluster health check part of upgrade pre-checks

### PR DESCRIPTION
**Pull request by jsuchome**
Backport of https://github.com/crowbar/crowbar-core/pull/637

### CODE REVIEW

**Comment by jsuchome** [comment]
<a href="https:&#x2F;&#x2F;trello.com&#x2F;c&#x2F;sKTTY1Wp&#x2F;65-3-s47p4-s46p13-implement-api-for-first-step-of-upgrade-checks"> (3) S47P4 (S46P13): Implement API for first step of upgrade: checks</a>

**Comment by mjura** [comment]
+1

**Comment by rsalevsky** [comment]
Same here: Can you prefix your commit messages with `upgrade:`?

**Comment by MaximilianMeister** [comment]
+1

**Pull request merged**
