### PR TITLE
bsc#958766 fix failed installation not returning any error message

### PR DESCRIPTION
**Pull request by MaximilianMeister**
https://bugzilla.suse.com/show_bug.cgi?id=958766

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
after all I have refactored the javascript a bit now to be less DRY

**Comment by rsalevsky** [comment]
+1

**Comment by bmwiedemann** [comment]
+1 if it still works.

**Comment by MaximilianMeister** [comment]
>  if it still works.

I have tested it a few times

**Comment by aplanas** [comment]
> I have tested it a few times
+1

**Pull request merged**
