### PR TITLE
Replace old status LED's

### PR DESCRIPTION
**Pull request by rsalevsky**
This change is based on the changes in our SUSE design branch.

### CODE REVIEW

**Comment by aplanas** [comment]
+1

Are there more changes in the queue? If so maybe we can add all together

**Comment by vuntz** [comment]
-1, some of the images are not updated, which will result in very weird behavior.

**Comment by vuntz** [comment]
Missing one is yellow-green-spin.png

**Comment by rsalevsky** [comment]
@vuntz Thanks, missed that one.

@aplanas Yep, but I prefer to put every change in one PR because I lost the overview completely.

**Comment by aplanas** [comment]
> @aplanas Yep, but I prefer to put every change in one PR because I lost the overview in the design branch completely.

But this will put UI in a very funny stages if we merge it out of order.

**Comment by rsalevsky** [comment]
Nop, I started already with grouping them so they are independently.

**Comment by vuntz** [comment]
+1

**Pull request merged**
