### PR TITLE
add specs for the Crowbar::Installer library

### PR DESCRIPTION
**Pull request by MaximilianMeister**

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
rebased

**Comment by rsalevsky** [comment]
+1

**Comment by vuntz** [comment]
LGTM

**Comment by MaximilianMeister** [comment]
@tboerger can you please have a look here?

**Comment by MaximilianMeister** [comment]
gating failed in cct's manila tests (I think that is also happening elsewhere), so likely not introduced by this PR

**Comment by tboerger** [comment]
Cool
:+1:

**Comment by tboerger** [comment]
> This branch is out-of-date with the base branch

**Comment by MaximilianMeister** [comment]
@rsalevsky is your +1 still valid?

**Comment by rsalevsky** [comment]
Still +1

**Pull request merged**
