### PR TITLE
[stable/3.0] determine the best upgrade mode

### PR DESCRIPTION
**Pull request by MaximilianMeister**
Backport of https://github.com/crowbar/crowbar-core/pull/744

### CODE REVIEW

**Comment by Itxaka** [comment]
Did github died and all the checks died because of that? Nothing seems to be reporting ¬_¬

**Comment by aspiers** [comment]
Not sure why https://ci.suse.de/job/cloud-crowbar-testbuild-pr/7182/ failed - trying a rebuild.

**Comment by MaximilianMeister** [comment]
old build got stuck in tempest https://ci.suse.de/job/openstack-mkcloud/38716/console

triggered another run

**Comment by Itxaka** [comment]
retriggered

**Comment by jsuchome** [comment]
Please add also the commit about executing ha presence check always

**Comment by MaximilianMeister** [comment]
> Please add also the commit about executing ha presence check always

https://github.com/crowbar/crowbar-core/pull/748 is not merged yet because of gating abortions, I'll retrigger there

**Comment by skazi0** [comment]
It's more important to have the backport merged as this is the place where this functionality will be used for the 6->7 upgrade.

**Comment by MaximilianMeister** [comment]
@jsuchome can you backport the `ha_presence` check? without that, it makes no sense to backport #748

**Comment by jsuchome** [comment]
@MaximilianMeister https://github.com/crowbar/crowbar-core/pull/751

**Comment by MaximilianMeister** [comment]
@jsuchome rebased

**Comment by MaximilianMeister** [comment]
rebased to trigger new gating

**Pull request merged**
