### PR TITLE
Prepare for Cloud 7

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by aplanas** [comment]
PR not found!. <sub>Sorry, I can help it :(</sub>

**Comment by dirkmueller** [comment]
@aplanas  :-)

**Comment by vuntz** [comment]
You probably need to change suse-12.1 to suse-12.2 in the file (except for SES?)

**Comment by vuntz** [comment]
Btw, do we really need to switch to SP2 now? I'm all for doing it early, but doing it while we're branching is a bit ambitious as I'm pretty sure it adds to the complexity of getting the gating working.

**Comment by dirkmueller** [comment]
@vuntz we're not switchign to SP2. but the project repository names are already SP2 based (but we actually build against SP1)

**Comment by dirkmueller** [comment]
I can't change suse-12.1 to 12.2 yet since mkcloud isn't prepared for that. This change is needed so that mkcloud does something (otherwise it rejects a media built from D:C:7 as invalid)

**Comment by vuntz** [comment]
Hrm, okay. Then +1, and let's hope it fixes gating for master...

**Comment by rsalevsky** [comment]
+1

**Pull request merged**
