### PR TITLE
Added API calls for repositories checks to the UI

### PR DESCRIPTION
**Pull request by jsuchome**

### CODE REVIEW

**Comment by jsuchome** [comment]
`repositories` should actually be called silently, and the page be shown only if the check fails. Hm.

**Comment by rhafer** [comment]
+1

**Comment by jsuchome** [comment]
I'm not sure if we still need this because the final wizard UI seems to be merged

**Comment by rsalevsky** [comment]
I stared working to integrate all this backend stuff into the final wizard.

**Comment by jsuchome** [comment]
@rsalevsky ah, thanks!

**Comment by rsalevsky** [comment]
See #221

**Pull request closed without merging**
