### PR TITLE
Raise gem version to new package versions

### PR DESCRIPTION
**Pull request by rsalevsky**

### CODE REVIEW

**Comment by tboerger** [comment]
You should raise the `Gemfile` versions as well.

**Comment by dirkmueller** [comment]
also chef/cookbooks/crowbar/recipes/default.rb needs to be adjusted

**Comment by tboerger** [comment]
LGTM

**Comment by dirkmueller** [comment]
+1

**Comment by vuntz** [comment]
Do you intend to update also other gems in this PR, or is this  a later step? (hashie, for instance)

**Comment by rsalevsky** [comment]
I think we should not mix the rails 4.2 upgrade and the gem version upgrade to SP1. So I prefer to open another PR for this.

**Comment by vuntz** [comment]
+1

**Comment by vuntz** [comment]
@rsalevsky we can merge (as, well, we have the patch in our package anyway now); were you planning anything label, or can we drop the "do not merge yet" label and merge?

**Comment by dirkmueller** [comment]
finished testing, merging.

**Pull request merged**
