### PR TITLE
Revert jquery and bootstrap bump

### PR DESCRIPTION
**Pull request by vuntz**
This reverts https://github.com/crowbar/crowbar-core/pull/63 as we seem to have a broken webui with the new jquery.

### CODE REVIEW

**Comment by tboerger** [comment]
It should be pretty bad to revert this as the new wizard screen and so on relies on the new bootstrap version.

**Comment by rsalevsky** [comment]
It seams this is just an issue with Firefox with Chrome it the migrate plugin works as expected.

I'm against the revert because the fix should be easy for an jquery expert and Ken started already with rewriting stuff to use the new bootstrap. It also blocks current cards in our sprint.

**Comment by vuntz** [comment]
@tboerger @rsalevsky really, the proposal is to revert it because noone is fixing it right now. That doesn't mean that we won't add it back later, but this is blocking the milestone... If someone fixes the bug, then of course it's better.

**Comment by vuntz** [comment]
> It seams this is just an issue with Firefox with Chrome it the migrate plugin works as expected.

The UI is also broken in chromium, btw.

**Comment by rsalevsky** [comment]
@tboerger As far as I know @tboerger works already on this.

**Comment by dirkmueller** [comment]
Whats the timeline for a fix ? we ought to release the milestone 9 days ago and this is something that got merged and is breaking stuff even though I asked to delay the merge until after the milestone was cut..

**Comment by toabctl** [comment]
I added this PR to the package for now to be able to continue with M6

**Comment by dirkmueller** [comment]
@toabctl the problem with having the revert only in the package is that it most likely breaks all other PR's gating

**Comment by toabctl** [comment]
@dirkmueller in this case it's just UI changes which shouldn't break gating I think

**Comment by tboerger** [comment]
Closed in favor of https://github.com/crowbar/crowbar-core/pull/77 and https://github.com/crowbar/crowbar-ha/pull/31

**Pull request closed without merging**
