### PR TITLE
delete backup from filesystem after restore (bsc#966489)

### PR DESCRIPTION
**Pull request by MaximilianMeister**

### CODE REVIEW

**Comment by rsalevsky** [comment]
Instead of deleting it we should add it to the database again after restore. This makes IMHO more sense and it's the same amount of work.

**Comment by rsalevsky** [comment]
Just got a other idea, we can just amend the current backup table dump to the yaml_db file in the backup.  Due to we don't backup the backup table we should have no conflict.

**Comment by tboerger** [comment]
Needs rebase but otherwise :+1:

**Comment by MaximilianMeister** [comment]
rebased

**Comment by jsuchome** [comment]
Tested, seems to work well +1

**Comment by vuntz** [comment]
Was there some green gating before we branched?

**Comment by vuntz** [comment]
+1, but need some green gating.

**Comment by MaximilianMeister** [comment]
> but need some green gating.

retriggered

**Comment by rsalevsky** [comment]
+1

**Comment by vuntz** [comment]
Can you backport to 3.0?

**Pull request merged**
