### PR TITLE
Fix key checksum

### PR DESCRIPTION
**Pull request by dirkmueller**
For some reason or signing key changed. Adjust

### CODE REVIEW

**Comment by bmwiedemann** [comment]
+1 as a quick fix
so someone did osc signkey --extend because the expiration time arrived... but what we really should do is match the gpg fingerprint, which does not change when extending the validity period.

**Comment by rsalevsky** [comment]
+1

**Comment by MaximilianMeister** [comment]
+1

**Comment by aplanas** [comment]
There is a fail in C6, and I think that something needs to be backported in https://github.com/crowbar/crowbar/blob/stable/3.0/scripts/install-chef-suse.sh#L521

**Comment by aplanas** [comment]
Also +1

**Pull request merged**
