### PR TITLE
upgrade: Adapt admin repository check

### PR DESCRIPTION
**Pull request by MaximilianMeister**
this is not a straight backport, so I haven't cherry-picked it

https://github.com/crowbar/crowbar-core/pull/989/commits/24302a8e48b2e63da9d88894d4a1faf00ea89540

partial backport of https://github.com/crowbar/crowbar-core/pull/989

### CODE REVIEW

**Comment by jsuchome** [comment]
With this patch, crowbartcl output looks like this: http://pastebin.nue.suse.com/19818/src 

When the repository is missing, it is actually listed twice, once as required and once as missing. I would think seeing it as missing should be enough (and if none is missing, no need to show any repo). What do the others think?

**Comment by jsuchome** [comment]
Also, we're listing **Cloud** repo now.
Is it really necessary when there's **SUSE-OpenStack-Cloud-7-Pool** ? @vuntz I'm kind of confused here, could you shed some light ?

**Comment by skazi0** [comment]
[crowbarctl should show nice names for missing repositories](https://trello.com/c/xr2UOZyN/261-crowbarctl-should-show-nice-names-for-missing-repositories)

**Comment by vuntz** [comment]
> Also, we're listing Cloud repo now.
> Is it really necessary when there's SUSE-OpenStack-Cloud-7-Pool ? @vuntz I'm kind of confused here, could you shed some light ? (This also applies to #989 which has nicer example output)

https://trello.com/c/4YsHrqUW/270-5-simplify-repo-setup

In short, right now, I think we require the Cloud repo during install; but it's actually not needed if Pool is there, indeed.

**Comment by MaximilianMeister** [comment]
> In short, right now, I think we require the Cloud repo during install; but it's actually not needed if Pool is there, indeed.

updated, thanks for the hint

**Comment by MaximilianMeister** [comment]
fixed the commit hash in the commit message, as there was a minor change (comment) on the cloud7 side

**Pull request merged**
