### PR TITLE
utils: Use new HA helpers to fetch the VIP of a hostname

### PR DESCRIPTION
**Pull request by vuntz**
Depends on https://github.com/crowbar/crowbar-ha/pull/120

### CODE REVIEW

**Comment by toabctl** [comment]
+1 (retriggering with HA cloud; passed with develcloud7 nonHA)

**Comment by nicolasbock** [comment]
+1

**Comment by vuntz** [comment]
> (retriggering with HA cloud; passed with develcloud7 nonHA)

This failed, but likely because the package built by gating was outdated; I re-triggered that, and then we'll need to re-trigger gating with HA.

**Comment by abel-navarro** [comment]
+1

**Pull request merged**
