### PR TITLE
Modified crowbar theme as per new colors

### PR DESCRIPTION
**Pull request by bisht-richa**

### CODE REVIEW

**Comment by vuntz** [comment]
Are the changes required for upstream, or for our branding package?

**Comment by rsalevsky** [comment]
@vuntz We have to split this somehow but I had no time so far to look into this.

**Comment by rsalevsky** [comment]
@bisht-richa We also have to change the logo in the branding package (https://build.suse.de/package/show/Devel:Cloud:7:Staging/crowbar-core-branding-SOC). Can you send me the updated logo via mail?

**Comment by bisht-richa** [comment]
@rsalevsky I have mailed you new logo.

**Comment by rsalevsky** [comment]
I opened a new PR with some small changes.

**Pull request closed without merging**
