### PR TITLE
Fix dnsmasq listening on a IPv4 only host (bsc#967236)

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by vuntz** [comment]
cc @bmwiedemann since he submitted the IPv6 patch.

**Comment by vuntz** [comment]
This is https://bugzilla.suse.com/show_bug.cgi?id=967236

**Comment by bmwiedemann** [comment]
+1

**Comment by dirkmueller** [comment]
@bmwiedemann we haven't reviewed any of the access control list restrictions for ipv6 compatibility

**Pull request merged**
