### PR TITLE
Sync crowbar service with chef template

### PR DESCRIPTION
**Pull request by rsalevsky**

### CODE REVIEW

**Comment by toabctl** [comment]
Why do we need a chef template and a .service file? Isn't one enough?

**Comment by vuntz** [comment]
+1

**Comment by vuntz** [comment]
@toabctl the non-template version is used in the package, so that crowbar can be started prior to chef having run.

**Comment by toabctl** [comment]
+1

**Comment by aspiers** [comment]
@vuntz So why do we need the template version at all?  And why don't we need `ExecStop` and `ExecReload`?

**Pull request merged**
