### PR TITLE
Move code away from CrowbarService

### PR DESCRIPTION
**Pull request by vuntz**
There's quite some code in there that shouldn't be in this file. So let's start cleaning that up.

FWIW, a lot of the upgrade methods should likely be moved, but I'm unclear where to move them (I don't believe they should go in lib/). I guess someone else could do that in a later PR, though.

### CODE REVIEW

**Comment by vuntz** [comment]
(Apologies for the hound spam; changing old code is pretty painful :/)

**Comment by vuntz** [comment]
Re-triggered gating with https://github.com/crowbar/crowbar-openstack/pull/423

**Comment by toabctl** [comment]
+1 (but gating needs retrigger)

**Comment by vuntz** [comment]
Had to rebase...

**Comment by nicolasbock** [comment]
+1

**Pull request merged**
