### PR TITLE
Add lgtm.co configuration file

### PR DESCRIPTION
**Pull request by rsalevsky**

### CODE REVIEW

**Comment by toabctl** [comment]
Let's try it. +1

**Comment by MaximilianMeister** [comment]
+1

**Comment by tboerger** [comment]
YEAH! +100

**Comment by MaximilianMeister** [comment]
but somehow it doesn't work yet, see e.g. https://github.com/crowbar/crowbar-core/pull/428
@rsalevsky can you check the configuration?

**Comment by tboerger** [comment]
> but somehow it doesn't work yet, see e.g. #428
> @rsalevsky can you check the configuration?

Already fixed, wrong maintainers group name.

**Comment by MaximilianMeister** [comment]
I just (indirectly) gave a +1 on my own PR and lgtm counted it. IMO it should not do that under any circumstance

see https://github.com/crowbar/crowbar-core/pull/430

**Comment by rsalevsky** [comment]
@MaximilianMeister Can you open a new issue in https://github.com/lgtmco/lgtm/issues?

**Comment by MaximilianMeister** [comment]
> Can you open a new issue at https://github.com/lgtmco/lgtm/issues?

https://github.com/lgtmco/lgtm/issues/11

**Pull request merged**
