### PR TITLE
also backup /etc/crowbar to restore before the installation

### PR DESCRIPTION
**Pull request by MaximilianMeister**
install-chef-suse will pick up the files from there

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
@vuntz  @rhafer are there some files that need special treatment here, or is it enough to just place them there before the installer?

**Comment by vuntz** [comment]
> is it enough to just place them there before the installer?

Should be enough; will test your patch right now.

**Comment by vuntz** [comment]
Works, +1.

**Comment by vuntz** [comment]
Works, +1.

**Comment by aplanas** [comment]
+1

**Pull request merged**
