### PR TITLE
add common glance user+group (bsc#968251)

### PR DESCRIPTION
**Pull request by bmwiedemann**
https://bugzilla.suse.com/show_bug.cgi?id=968251
for making HA glance on shared NFS backend storage work

### CODE REVIEW

**Comment by jsuchome** [comment]
This works correctly as expected, new installed nodes get the glance user and group with same UID and GID.

However, why do we need to patch crowbar_register when we set the group and user in autoyast profile?

**Comment by bhdn** [comment]
IIUC, the node can be set up manually, thus not relying on autoyast.

**Comment by jsuchome** [comment]
@bhdn Makes sense. +1 then

**Comment by rhafer** [comment]
+1 (I guess we want to backport this to stable/3.0 ?)

**Pull request merged**
