### PR TITLE
Wrap parameters

### PR DESCRIPTION
**Pull request by rsalevsky**
Obsoletes https://github.com/crowbar/crowbar-client/pull/64

### CODE REVIEW

**Comment by vuntz** [comment]
Typo in commit message: wrappend

**Comment by MaximilianMeister** [comment]
stupid question, why do we create a namespace `backup` and having to do this wrapping afterwards? doesn't say in the commit message.

**Comment by rsalevsky** [comment]
@MaximilianMeister With this we make sure that we just trust allowed params and at the same time we make sure that we have all required data. `:file` is in this case very special because it's just temporary and it's not part of the database.

**Comment by vuntz** [comment]
I don't understand why this is needed. Is this purely for convenience? Or is this to allow clients written in a lazy way?

**Comment by rsalevsky** [comment]
This change is needed that we can send json requests with params without a namespace. For html requests it is recommended to namespace them but for json requests it is in general not wanted because it makes the api requests more complex. The rails wrapper just ensures that both ways works for json.

We need this PR to unblock backup & restore gating and fix backup commands in crowbarctl.

**Comment by MaximilianMeister** [comment]
> This change is needed that we can send json requests with params without a namespace. For html requests it is recommended to namespace them but for json requests it is in general not wanted because it makes the api requests more complex. The rails wrapper just ensures that both ways works for json.

makes sense to me, can you please add this to the commit message?

and would be good if @tboerger could review this

**Comment by jdsn** [comment]
> and would be good if @tboerger could review this

@MaximilianMeister it was @tboerger who proposed this patch

**Comment by jdsn** [comment]
:+1:

**Comment by rsalevsky** [comment]
Updated commit message.

**Comment by vuntz** [comment]
> This change is needed that we can send json requests with params without a namespace. For html requests it is recommended to namespace them but for json requests it is in general not wanted because it makes the api requests more complex. The rails wrapper just ensures that both ways works for json.

I'm fine with the change, but why don't we do this for all controllers and only here?

**Comment by rsalevsky** [comment]
We do it for all controllers, this is done by the first commit. The second commit is just that we also include `:file` into the wrapping because this is not done by default due to https://github.com/rsalevsky/crowbar-core/blob/wrap_parameters/crowbar_framework/app/models/backup.rb#L21.

**Comment by vuntz** [comment]
Ah okay, thanks for the explanation.

So you get a LGTM from me, unfortunately, I'm not comfortable enough for a +1. (but feel free to change my LGTM to a +1 if you get a rails expert approving this)

**Comment by tboerger** [comment]
Even if it's already merged, :+1: :)

**Pull request merged**
