### PR TITLE
Add development gems for benchmarking

### PR DESCRIPTION
**Pull request by rsalevsky**
See [schneems/derailed_benchmarks](https://github.com/schneems/derailed_benchmarks) for more information.

This gems helps us the find performance issues in long term it would be also nice to have a basic benchmarking in the gating.

### CODE REVIEW

**Comment by MaximilianMeister** [comment]
if it helps

+1

**Comment by tboerger** [comment]
Just integration it into gating doesn't make really sense because nobody compares it with previous versions. But if that helps benachmarking why not...

**Comment by tboerger** [comment]
:+1:

**Comment by tboerger** [comment]
:+1:

**Comment by tboerger** [comment]
Needs rebase

**Comment by dirkmueller** [comment]
@rsalevsky rebase?

**Comment by jdsn** [comment]
:+1: lgtm

**Pull request merged**
