### PR TITLE
Multi-threaded node saving

### PR DESCRIPTION
**Pull request by skazi0**
**Why is this change necessary?**
Saving node data takes a lot of time when applying proposal for barclamps like dns or network which affect most of the nodes.

**How does it address the issue?**
With multiple chef-server workers running, saving multiple nodes in parallel gives significant performance improvement in large scale installations.

**Is there additional information worth sharing like links to a Trello
card, bug references, testing advice or dependencies to other pull
requests?**
https://trello.com/c/jGyRtgrr/195-save-node-data-in-parallel

### CODE REVIEW

**Comment by skazi0** [comment]
[Save node data in parallel](https://trello.com/c/jGyRtgrr/195-save-node-data-in-parallel)

**Comment by skazi0** [comment]
@jsuchome idea came from @vuntz :)
@nicolasbock in my test runs with ~230 nodes time to apply dns proposal went down by ~24% (from ~10:45 to ~8:10)

**Comment by Itxaka** [comment]
Im guessing that knowing that @nicolasbock is a scientists he wants raw data in order to reproduce the results independently. Science! :P

**Comment by nicolasbock** [comment]
Yes, that's right @Itxaka, I always insist on evidence. :wink: You really can't just believe what you read on the Internet :smile:

**Comment by nicolasbock** [comment]
And that's an impressive performance boost @skazi0 !

**Pull request merged**
