### PR TITLE
[stable/3.0] add some more logging

### PR DESCRIPTION
**Pull request by MaximilianMeister**
that makes it easier to debug errors, esperially around the process
forking that happens in run_remote_chef_client

### CODE REVIEW

**Comment by rsalevsky** [comment]
Can you please add the prefix to the commit message?

**Comment by MaximilianMeister** [comment]
> Can you please add the prefix to the commit message?

it's unrelated to the upgrade. shall i add some prefix anyways?

**Comment by rsalevsky** [comment]
@MaximilianMeister yes would be nice

**Comment by vuntz** [comment]
If it's unrelated to the upgrade process, shouldn't this go to master first?

**Comment by MaximilianMeister** [comment]
> If it's unrelated to the upgrade process, shouldn't this go to master first?

* it happened on cloud6
* in master the code is a bit different (we dropped lots of code and we don't use the `Kernel::Fork` anymore). 

so it wouldn't be backportable anyways. but TBH i haven't checked if the code in master also needs more logging.

**Comment by rsalevsky** [comment]
@MaximilianMeister Can you rebase to trigger the gating?

**Comment by MaximilianMeister** [comment]
rebased

**Comment by vuntz** [comment]
FWIW, I'd prefer to have https://github.com/crowbar/crowbar-core/pull/923 merged instead.

**Comment by MaximilianMeister** [comment]
> FWIW, I'd prefer to have #923 merged instead.

ok, closing...

**Pull request closed without merging**
