### PR TITLE
Set a timeout for sessions

### PR DESCRIPTION
**Pull request by dirkmueller**

### CODE REVIEW

**Comment by vuntz** [comment]
So I think we want your change, but we need more than that. See http://guides.rubyonrails.org/security.html#session-expiry

**Comment by vuntz** [comment]
See https://github.com/crowbar/crowbar-core/pull/257 for session sweeping.

+1 for your patch still.

**Comment by aplanas** [comment]
+1 if this together with #257 address the full session problem

**Comment by dirkmueller** [comment]
@vuntz do we still need this one when the other one is merged?

**Comment by vuntz** [comment]
> @vuntz do we still need this one when the other one is merged?

Yes, your patch sets the timeout in the cookie. Which we want :-)

**Comment by dirkmueller** [comment]
ok then..

**Comment by tboerger** [comment]
What? 4 hours only?

**Pull request merged**
