### PR TITLE
Set rake to version to 10.3.2

### PR DESCRIPTION
**Pull request by rsalevsky**

### CODE REVIEW

**Comment by tboerger** [comment]
Travis still fails because of malicious rails version.

**Comment by tboerger** [comment]
Otherwise :+1:

**Comment by bmwiedemann** [comment]
:+1:

**Comment by rsalevsky** [comment]
Gating fails: Could not find gem 'rake (~> 10.3.2) ruby' in the gems available on this machine. (Bundler::GemNotFound)

**Comment by bmwiedemann** [comment]
Actually, it is not failing from rake here, but from the bundle-audit complaining about rails-4.2.6 (which we dont use in the product anyway)

**Comment by vuntz** [comment]
> Actually, it is not failing from rake here, but from the bundle-audit complaining about rails-4.2.6 (which we dont use in the product anyway)

Can we set these to 4.2.2 (which is what we use in our packages)? I'm not sure if "Solution: upgrade to ~> 5.0.0.beta1.1, ~> 4.2.5.1, >= 4.1.14.1, ~> 4.1.14" means a version that matches all of these criterias or one of these, though...

**Comment by bmwiedemann** [comment]
Also, in SLE-12-SP1 we have rake 10.1.0 as part of ruby-2.1 ... I wonder if there is a way to make all those checks happy or if we should drop some of them.

**Comment by MaximilianMeister** [comment]
travis was green here https://github.com/crowbar/crowbar-core/pull/371

maybe we don't need it anymore?

**Comment by tboerger** [comment]
> Can we set these to 4.2.2 (which is what we use in our packages)? I'm not sure if "Solution: upgrade to ~> 5.0.0.beta1.1, ~> 4.2.5.1, >= 4.1.14.1, ~> 4.1.14" means a version that matches all of these criterias or one of these, though...

Oru version is vulnerable, we should upgrade to `4.2.5.1`

**Comment by rsalevsky** [comment]
Seams to work again.

**Comment by tboerger** [comment]
We should revert the merged pull requests for the other repos.

**Pull request closed without merging**
