### PR TITLE
upgrade: report failure to the UI in case upgrade/restore fails early (bsc#967785)

### PR DESCRIPTION
**Pull request by MaximilianMeister**

### CODE REVIEW

**Comment by vuntz** [comment]
Not really sure about the javascript bit, but I'll trust you here. +1.

**Comment by MaximilianMeister** [comment]
> Not really sure about the javascript bit, but I'll trust you here. 

@vuntz if you merge https://github.com/crowbar/crowbar-core/pull/382 before, then we can drop the javascript part here :-) as it will not be needed anymore

**Comment by rsalevsky** [comment]
+1

**Comment by vuntz** [comment]
> > Not really sure about the javascript bit, but I'll trust you here.
> 
> @vuntz if you merge #382 before, then we can drop the javascript part here :-) as it will not be needed anymore

So should we wait for that?

**Comment by MaximilianMeister** [comment]
> So should we wait for that?

I just thought because it has 2 plus ones it will be merged quicker. i also commented there. It's up to you, just tell me what we should do here.

**Comment by vuntz** [comment]
> I just thought because it has 2 plus ones it will be merged quicker. i also commented there. It's up to you, just tell me what we should do here.

We merged the other PR :-)

**Comment by vuntz** [comment]
Still +1.

**Comment by MaximilianMeister** [comment]
@vuntz can you merge this?

**Comment by vuntz** [comment]
> @vuntz can you merge this?

We're missing a +1 after the last change (I'm retriggering gating, btw).

**Comment by MaximilianMeister** [comment]
> We're missing a +1 after the last change

is this really necessary? we just dropped the javascript bit

**Comment by vuntz** [comment]
> is this really necessary? we just dropped the javascript bit

You also rebased, which sometimes create issues. Until github provides a nice way to diff between the old patch and the new patch, I (nearly) always rely on two +1 after the last change.

**Comment by MaximilianMeister** [comment]
> I (nearly) always rely on two +1 after the last change.

okay, then we (or everybody who can merge) should all do that

**Comment by MaximilianMeister** [comment]
@rsalevsky can you please give your +1 another time so we can merge this?

**Comment by rsalevsky** [comment]
+1

**Comment by vuntz** [comment]
Gating failed in cct, merging.

Can you backport to 3.0?

**Pull request merged**
