### PR TITLE
catch RuntimeError instead of failing

### PR DESCRIPTION
**Pull request by MaximilianMeister**
trying to create a nova proposal without neutron led to the page
"We are sorry, but something went wrong"

### CODE REVIEW

**Comment by gosipyan** [comment]
Fix has been verified on virtual env  and it works now.

**Comment by vuntz** [comment]
Typo in commit message: s/led/lead/

**Comment by vuntz** [comment]
+1

**Comment by aplanas** [comment]
+1

**Comment by vuntz** [comment]
@MaximilianMeister feel free to merge after fixing the typo.

**Comment by MaximilianMeister** [comment]
@vuntz done

> feel free to merge after fixing the typo.

well I would if I could. can you please merge?

**Comment by tboerger** [comment]
Instead of doing that in the controller you should do that in the model at https://github.com/crowbar/crowbar-core/blob/master/crowbar_framework/app/models/service_object.rb#L519

**Pull request merged**
