### PR TITLE
Set proper versions to check for upgrade admin repos

### PR DESCRIPTION
**Pull request by Itxaka**
Sets the versions to check to suse 12.2 and openstack 7

### CODE REVIEW

**Comment by Itxaka** [comment]
[(3) S49P14 bsc#999946 - [Upgrade] Check for repositories on admin server only checks for product](https://trello.com/c/sl8vHEaY/146-3-s49p14-bsc-999946-upgrade-check-for-repositories-on-admin-server-only-checks-for-product)

**Comment by jsuchome** [comment]
No, these numbers are actually correct. The point is, admin server repo check is run from the non-upgraded Cloud, so for our case it's from Cloud6. This code is master, so Cloud7, and admin repo checks here are prepared for upgrading to Cloud8

**Comment by Itxaka** [comment]
@jsuchome This is a PR against 3.0, cloud6. Im guessing that the original change was doing on master, then backported to 3.0 with no changes. This will never work on cloud6 to 7 upgrade!

**Comment by jsuchome** [comment]
Ah, sorry, you are right.

But there's already an open PR for that... https://github.com/crowbar/crowbar-core/pull/718

**Comment by Itxaka** [comment]
Ahh nice, thanks for pointing it out @jsuchome !

**Pull request closed without merging**
