### PR TITLE
Remove _repos prefix from missing and inactive repos

### PR DESCRIPTION
**Pull request by rsalevsky**
The _repos prefix only provides already given information. We know that
we are working with repos at this point.

It also makes the output better readable, see: https://github.com/crowbar/crowbar-client/pull/104#issuecomment-246263007

### CODE REVIEW

**Comment by jsuchome** [comment]
Aren't we checking for those keys anywhere?

**Comment by jsuchome** [comment]
+1

**Comment by nicolasbock** [comment]
+1

**Comment by MaximilianMeister** [comment]
> Aren't we checking for those keys anywhere?

what about `app/models/api/crowbar/crowbar.rb`?

**Comment by MaximilianMeister** [comment]
and the node specs and fixtures, since https://github.com/crowbar/crowbar-core/pull/652 got merged

**Comment by nicolasbock** [comment]
Hmm, given @MaximilianMeister comments, I'll retract my +1 for now....

**Comment by rsalevsky** [comment]
Rebased

**Comment by MaximilianMeister** [comment]
+1

**Comment by vuntz** [comment]
+1

**Comment by aspiers** [comment]
+1, not that you need it.

**Comment by nicolasbock** [comment]
+1

**Pull request merged**
