### PR TITLE
be more robust with deleted nodes

### PR DESCRIPTION
**Pull request by bmwiedemann**

### CODE REVIEW

**Comment by bmwiedemann** [comment]
@rhafer yes, we (partially) deleted a node and got a [] access on nil in this line, that went away after applying this patch.

**Comment by rhafer** [comment]
> yes, we (partially) deleted a node and got a [] access on nil in this line, that went away after applying this patch.

@bmwiedemann Thanks. "(partially) deleted" means what? Just the node-role, just the node-object, just some attributes or something else?

**Comment by bmwiedemann** [comment]
We clicked forget in crowbar, but the node never fully went away, so I also did a `knife node delete $NODE` and a `knife role delete $NODEROLE` to get rid of it, but there were probably some parts left, because the next discovery failed with "cannot create $NODE - already exists"

**Comment by aspiers** [comment]
+1

**Comment by aspiers** [comment]
Wake up, LGTM! +1 again

**Pull request merged**
